config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: 'confirmations'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  mount Ckeditor::Engine => '/ckeditor'

  root "home#index"
  get 'contact', to: "home#index#contact"
  get 'health-check', to: 'home#health_check'
  get 'about-us', to: 'about_us#index'
  get 'faqs', to: 'faqs#index'
  get 'features', to: 'features#index'
  get 'how-it-works', to: 'how_it_works#index'
  get 'contact', to: 'contacts#index'
  get 'privacy-policy', to: 'privacy_policy#index'
  get 'gdpr-cpaground', to: 'gdpr#index'
  get 'thank_you/:id', to: 'home#thank_you', as: "thank_you"
  get 'waiting_verified/:id', to: 'home#waiting_verified', as: "waiting_verified"
  get 'under-maintenance', to: 'home#under_maintenance', as: 'under_maintenance'
  get '404-not-found', to: 'home#not_found_page', as: 'not_found_page'
  get 'lombok', to: 'home#lombok', as: 'lombok'
  resources :contacts
  resources :subscribers, only: [:create] do 
    collection do
      get :subscribe
      get :unsubscribe
    end
  end

  resources :xhrs do
    collection do
      get :cities
      get :get_box_report
      get :get_balances
      get :get_revenues
      get :get_commisions
      get :get_notifications
      get :get_campaign
      get :get_campaign_date_form
      get :get_offer_cr
      get :get_payment_owners
      get :get_convertion_report
      get :change_convertion_report
    end
  end

  namespace :admins do
    resources :dashboards
    resources :owners
    resources :invoice_owners do
      member do
        put :change_status
      end
    end
    resources :admins
    resources :account_managers do
      member do
        put :change_status
        get :detail_report
      end
      collection do
        get :multiple_action
      end
    end
    resources :publishers do
      member do
        put :change_status
        get :detail_report
      end
      collection do
        get :multiple_action
        get :list_email
      end
    end
    resources :campaigns do
      collection do
        get :multiple_action
        post :import
      end
      member do
        put :change_status
        get :click_notif
      end
    end
    resources :category_campaigns do
      collection do
        get :multiple_action
        get :multiple_action_targeting
        get :multiple_action_banner_image
        post :import
        post :import_per_offer
      end
      member do
        put :change_status
        delete :delete_targeting
        delete :delete_banner_image
      end
    end
    resources :report_campaign_snapshots do
      member do
        put :change_convertion_report
        delete :delete_convertion_report
      end
    end
    resources :contacts
    resources :web_settings
    resources :payment_snapshots do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :layout_themes do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :request_landing_pages do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
        get :click_notif
      end
    end
    resources :subscribers, only: [:index, :show, :destroy] do
      member do
        put :change_status
      end
    end
    resources :blogs do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :forums do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
        delete :delete_comment
      end
    end
    resources :feeds do
      collection do
        post :comment_create
      end
    end
    resources :invoices do
      member do
        put :change_status
      end
    end
    resources :groups do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :access_offers do
      collection do
        get :multiple_action
      end
    end
    resources :reports do
      collection do
        get :input
      end
      member do
        delete :delete_report_item
      end
      collection do
        get :multiple_action
      end
    end
    resources :informations do
      member do
        put :change_status
      end
      collection do
        get :multiple_action
      end
    end
    resources :permission_referral_publishers
    resources :commisions
    resources :payment_commisions do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :messages
  end

  namespace :account_managers do
    resources :dashboards do
      collection do
        resources :rankings
      end
    end
    resources :campaigns do
      member do
        get :click_notif
        put :approvement
      end
    end
    resources :offers
    resources :profiles
    resources :activities
    resources :forums do
      member do
        delete :delete_comment
      end
    end
    resources :blogs do
      collection do
        post :comment_create
      end
    end
    resources :referrals
    resources :payments do
      member do
        get :click_notif
      end
    end
    resources :publishers do
      member do
        get :click_message
        get :detail_report
        put :change_status
        put :suspended
      end
    end
    resources :messages do
      collection do
        post :blast_message
      end
    end
    resources :feeds do
      collection do
        post :comment_create
        post :like_create
      end
    end
    resources :request_landing_pages do
      member do
        get :click_notif
      end
    end
    resources :notifications
    resources :groups do
      member do
        # put :change_status
        put :change_status_group_coverage
        get :click_notif
      end
    end
    resources :offers do
      member do
        get :click_notif
        put :checked
        put :change_status
      end
    end
    resources :reports
    resources :permission_referral_publishers
    resources :commisions
  end

  namespace :publishers do
    # get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :dashboards
    resources :campaigns do
      member do
        get :click_notif
      end
    end
    resources :offers do
      member do
        get :click_notif
        put :checked
        put :change_status
      end
    end
    resources :profiles
    resources :activities
    resources :forums
    resources :blogs do
      collection do
        post :comment_create
      end
    end
    resources :referrals
    resources :payments do
      member do
        get :click_notif
      end
    end
    resources :managers
    resources :messages
    resources :feeds do
      collection do
        post :comment_create
        post :like_create
      end
    end
    resources :request_landing_pages do
      member do
        get :click_notif
        put :change_status
      end
      collection do
        get :download_lp
      end
    end
    resources :notifications
    resources :groups do
      collection do
        post :join
      end
      member do
        get :click_notif
      end
    end
    resources :access_offers
    resources :reports
    resources :referral_publishers
    resources :commisions
    resources :payment_commisions do
      member do
        get :click_notif
      end
    end
    resources :offer_commisions
  end

  namespace :api do
    resources :lp do
      collection do
        get :track_visit
        get :postback
        get :get_campaigns
      end
    end
  end
  get 'postback', to: 'api/lp#postback', as: "postback"
end

app/controllers/account_managers/publishers_controller.rb
class AccountManagers::PublishersController < AccountManagers::ApplicationController
	before_action :class_name

  add_breadcrumb "dashboard", :account_managers_dashboards_path
  add_breadcrumb "publishers", :account_managers_publishers_path

  def index
    if params[:export] == 'true'
      @total_publishers = collection
    end
    
    @publishers = collection.page(params[:publishers_list]).per(6)
    @publishers_waiting_all = @account_manager.publishers.pending.confirmed.waiting_search_by(params).latest
    @publishers_waiting = @publishers_waiting_all.page(params[:publishers_waiting]).per(per_page)

    respond_to do |format|
      format.html 
      format.xls
      format.js
    end
  end

  def show
    add_breadcrumb "messages"
    resource
    if @publisher.account_manager_id == current_user.id
      @profile = @publisher.profile
      check_group_message_publisher(@account_manager.id, @publisher.id)

      if @latest_messages.where(from: @publisher.id).present?
        @latest_messages.where(from: @publisher.id).each do |m|
          m.status = 'read'
          m.save
        end
      end
    else
      redirect_to :back, alert: "You can not access this page because he/she is not your publisher."
    end
  end

  def detail_report
    add_breadcrumb "reports"
    resource

    # ---------- CGAWARDTRIP2018 -----------
    @cgaward = ReportCampaignSnapshot.where(publisher_id: @publisher.id).where(:sales.gte => 1)
                      .where(:campaign_date.gte => 'Mon, 1 Mar 2018'.to_date, :campaign_date.lte => @date)
                      .sum(:fee_publisher)
    @cgaward_percent = '%.4f' % (('%.4f' % (@cgaward.to_f/10000)).to_f * 100)
    # --------------------------------------

    get_analytic_report(@publisher, 'dashboard_am_publisher')
    if @convertion_reports.present?
      set_collection_convertion_report(params[:group_by], @convertion_reports, "publisher")
      # multipe_chart(@convertion_reports_list)
    end

    respond_to do |format|
      format.html 
      format.xls
      format.js
    end
  end

  def click_message
    message = Message.find(params[:message_id])
    message.status = "read"
    message.save

    redirect_to account_managers_publisher_path(params[:id])
  end

  def change_status
    @publisher = Publisher.find_by(id: params[:id])
    @publisher.verified = true
    if Rails.env.production?
      @publisher.admin_id = Admin.find_by(slug: 'winda').id
    else
      @publisher.admin_id = Admin.last.id
    end

    if @publisher.save
      verification_snapshot(@publisher)
      create_activity(@publisher, current_user.id, "verification publisher", "successfully verification publisher #{@publisher.username}")
      UserMailer.publisher_approved(@publisher).deliver_now! if @publisher.is_verified?
    else

    end

    respond_to do |format|
      format.js { render json: { status: 'Success', data: @publisher }, status: :ok }
    end
  end

  def suspended
    @publisher = Publisher.find_by(id: params[:id])
    @publisher.suspended = params[:publisher][:suspended]
    @publisher.suspended_message = params[:publisher][:suspended_message] if params[:publisher][:suspended_message].present?

    if @publisher.save
      if @publisher.suspended?
        create_activity(@publisher, current_user.id, "suspended publisher", "successfully suspended publisher #{@publisher.username}")
        UserMailer.publisher_suspended(@publisher).deliver_now!
      else
        @publisher.suspended_message = nil
        @publisher.save
        create_activity(@publisher, current_user.id, "activated publisher", "successfully activated publisher #{@publisher.username}")
        UserMailer.publisher_activated(@publisher).deliver_now!
      end
    else

    end

    respond_to do |format|
      format.js { render json: { status: 'Success', data: @publisher }, status: :ok }
    end
  end

  private
    def resource
      @publisher = Publisher.find params[:id]
    end

    def collection
      @publishers = @account_manager.publishers.verified.search_by(params)
    end

    def class_name
      @resource_name = 'Publisher'
      @collection_name = 'Publishers'
    end

    def verification_snapshot(publisher)
      verification_snapshot = VerificationSnapshot.new
      verification_snapshot.publisher_id = publisher.id
      verification_snapshot.admin_id = publisher.admin_id
      verification_snapshot.account_manager_id = current_user.id
      verification_snapshot.status = VerificationSnapshot::ACTIVE
      verification_snapshot.message = "#{current_user.username}(AM) has change verification status to #{verification_snapshot.status}."
      verification_snapshot.save
    end
end

app/controllers/account_managers/reports_controller.rb
class AccountManagers::ReportsController < AccountManagers::ApplicationController
  before_action :check_profile
  before_action :class_name

  add_breadcrumb "dashboard", :account_managers_dashboards_path
  add_breadcrumb "reports", :account_managers_reports_path

  def index
    @date = Time.zone.now.to_date

    unless params[:start_at].present? && params[:end_at].present?
      unless params[:status] == "visited"
        collection = @account_manager.convertion_reports.where(convertion_date: @date).have_sales
      else
        collection = @account_manager.convertion_reports.where(convertion_date: @date).visited
      end
    else
      unless params[:status] == "visited"
        collection = @account_manager.convertion_reports.have_sales.search_by(params)
      else
        collection = @account_manager.convertion_reports.visited.search_by(params)
      end
    end
    
    # multipe_chart(collection) unless params[:status] == "visited"
    set_collection_convertion_report(params[:group_by], collection, "publisher") rescue nil

    unless params[:status] == 'visited'
      @total_collection_approved = collection.approved.count rescue 0
      @total_collection_pending = collection.pending.count rescue 0
      @total_collection_reject = collection.where(status: "reject").count rescue 0

      @fee_approved = collection.approved.sum(:fee_publisher) rescue 0
      @fee_pending = collection.pending.sum(:fee_publisher) rescue 0
      @fee_reject = collection.where(status: "reject").sum(:fee_publisher) rescue 0

      if params[:export] == 'true'
        @total_convertion_reports = collection.have_sales_only.latest rescue nil
      end
    end
    
    respond_to do |format|
      format.html 
      format.xls
      format.js
    end
  end

  def show
    add_breadcrumb "#{params[:action]}"
    
    respond_to do |format|
      format.html 
      format.xls
      format.js
    end
  end

  private
    def resource
      @report = @account_manager.convertion_reports.find(params[:id])
    end

    def class_name
      @resource_name = 'Report'
      @collection_name = 'Reports'
    end
end

app/controllers/publishers/access_offers_controller.rb
class Publishers::AccessOffersController < Publishers::ApplicationController
	before_action :check_profile
	before_action :class_name

	def create
		@access_offer = AccessOffer.new params_permit
		@access_offer.publisher_id = current_user.id
		@access_offer.account_manager_id = current_user.account_manager_id
		@access_offer.status = AccessOffer::APPROVE

		if @access_offer.save
      @offer = @access_offer.offer
			create_activity(@offer, current_user.id, "Applied offer '#{@offer.name}' with code #{@offer.code}", "#{@access_offer.publisher.username} have successfully submitted a request to create a campaign on offer '#{@offer.name}' with code #{@offer.code}.")
			create_notification(@offer, @access_offer.account_manager_id, "#{@access_offer.publisher.username} applied offer '#{@offer.name}' with code #{@offer.code}", "please verify your publisher data before approval offer.")
			UserMailer.apply_access_offer(@access_offer).deliver_now!
			redirect_to :back, notice: "You have successfully submitted a request to create a campaign on offer '#{@access_offer.offer.name}' with code #{@offer.code}, please wait, our team will verify your data first."
		else
			redirect_to :back, alert: "Unsuccessfully applied offer."
		end
	end

	private

		def params_permit
			params.require(:access_offer).permit(:publisher_id, :account_manager_id, :category_campaign_id, :status, :checked, :message)
		end

		def class_name
			@resource_name = 'Offer'
			@collection_name = 'Offers'
		end
end

app/controllers/publishers/activities_controller.rb
class Publishers::ActivitiesController < Publishers::ApplicationController
  before_action :check_profile

  add_breadcrumb "dashboard", :publishers_dashboards_path
  add_breadcrumb "my activities", :publishers_activities_path
  
  def index
    @activities = @publisher.activities.latest.search_by(params).page(page).per(per_page)
  end
  
end

app/controllers/publishers/blogs_controller.rb
class Publishers::BlogsController < Publishers::ApplicationController
	before_action :check_profile

	add_breadcrumb "dashboard", :publishers_dashboards_path
	add_breadcrumb "blogs", :publishers_blogs_path
	
	def index
		@blogs = Blog.activated.latest.page(page).per(per_page)
	end

	def show
		add_breadcrumb "#{params[:action]}"
		@blog = Blog.find params[:id]
		@latest_blogs = Blog.not_in(id: @blog.id).activated.latest.limit(5)
		@blog_comments = @blog.feed_comments.latest.page(page).per(5)

		@blog.update(view_count: @blog.view_count + 1)
	end

	def comment_create
		@feed_comment = FeedComment.create(user_id: current_user.id, message: params[:message], feedable_id: params[:feedable_id], feedable_type: params[:feedable_type])
		
		respond_to do |format|
			format.js { render json: { status: 'Success', user_username: @feed_comment.user.username, user_avatar: @feed_comment.user.avatar.url(:thumb), data: @feed_comment}, status: :ok }
		end
	end
	
end

app/views/publishers/reports/_index.html.haml
- if current_user.is_publisher?
	- link_path = publishers_reports_path
- elsif current_user.is_account_manager?
	- link_path = account_managers_reports_path
- else
	- link_path = admins_reports_pat
#wrapper.content-offer-publisher.content-dashboard
	.js-breadcrumb
		= render 'publishers/reports/breadcrumb'
	.content.animate-panel.offers.responsive-content-offers
		.row
			= form_for :search, url: link_path, method: 'get', html: {class: 'js-form-submit', remote: true} do
				.js-box-calculation
					= render 'publishers/reports/box_calculation'
				.js-report-convertion
					= render 'publishers/reports/cart'
				.col-md-12
					.hpanel.responsive-hpanel
						.panel-body
							.row
								.col-xs-12.col-md-12
									#table-lists
										= render 'publishers/reports/lists'

	= render 'publishers/shared/footer'

:javascript
	$(document).ready(function() {
		$(document).on('change', '.js-onchange-group', function(){
			$('.js-form-submit').trigger('submit.rails');
			$(".spinner-load").show();
		});
	});

app/views/publishers/reports/_lists.html.haml
.row
	%div{ class: "#{params[:status] == "visited" ? 'col-xs-12 col-md-12' : 'col-xs-12 col-md-10'}"}
		.form-group
			- if current_user.is_publisher?
				= select_tag :group_by, options_for_select(['Campaign', 'Offer', 'Date', 'Country', 'Referrer', 'Device', 'Browser', 'Source', 'Sub1', 'Sub2'], params[:group_by]), prompt: 'Group By', class: 'js-onchange-group form-control'
			- else
				= select_tag :group_by, options_for_select(['Campaign', 'Offer', 'Date', 'IP Address', 'Country', 'Referrer', 'Device', 'Browser', 'Source', 'Sub1', 'Sub2'], params[:group_by]), prompt: 'Group By', class: 'js-onchange-group form-control'
	- unless params[:status] == "visited"
		.col-md-2.col-xs-12
			.form-group
				%a{ href: "#{controller_name.downcase}.xls?export=true&#{request.fullpath.split("?")[1]}", class: 'btn btn-success btn-block'}
					%i.fa.fa-file-excel-o
					&nbsp;
					Export to excel

- if @convertion_reports.present?
	.show-report-campaign-snapshots
		- if params[:group_by].blank?
			.responsive-tabel
				%table#example1.table.table-bordered.table-striped.tabel-width3
					%thead
						%tr
							%th.th-report Click Date
							%th Time
							%th Campaign
							%th Offer
							- unless current_user.is_publisher?
								%th Publisher
								%th IP Address
							%th Referrer
							%th Country
							%th Device
							%th Browser
							%th OS
							%th Source
							%th Sub1
							%th Sub2
							- unless params[:status] == "visited"
								%th Status
								%th Sales
								%th Revenue
					%tbody
						- if @convertion_reports.blank?
							%tr
								= render "shared/empty_blank"
						- else
							- @convertion_reports.each_with_index do |resource, index|
								- if current_user.is_admin?
									- link_path = admins_campaign_path(resource.campaign)
									- link_publisher_path = admins_publisher_path(resource.publisher)
									- revenue = resource.revenue
								- elsif current_user.is_account_manager?
									- link_path = account_managers_campaign_path(resource.campaign)
									- link_publisher_path = account_managers_publisher_path(resource.publisher)
									- revenue = resource.fee_publisher
								- elsif current_user.is_publisher?
									- link_path = publishers_campaign_path(resource.campaign)
									- revenue = resource.fee_publisher
								%tr
									%td
										%small
											= date_sort_time(resource.convertion_date)
									%td
										%small
											= get_time(resource.convertion_time)
									%td
										%small
											= link_to "(#{resource.campaign.code}) "+resource.campaign.title, link_path
									%td
										%small
											= resource.category_campaign.name
									- unless current_user.is_publisher?
										%td
											%small
												= link_to resource.publisher.username, link_publisher_path
										%td
											%small
												= resource.ip
									%td
										%small
											= resource.referrer
									%td
										%small
											= resource.country_code
									%td
										%small
											= resource.device
									%td
										%small
											= resource.browser
									%td
										%small
											= resource.os || '--'
									%td
										%small
											= resource.source || '--'
									%td
										%small
											= resource.sub1 || '--'
									%td
										%small
											= resource.sub2 || '--'
									- unless params[:status] == "visited"
										%td
											%small
												= resource.status
										%td
											%small
												= resource.sales > 0 ? 'Yes' : 'No'
										%td
											%small
												#{resource.status?} #{get_currency(revenue)}
											- if resource.category_campaign.is_cps? && params[:status] != "visited"
												%span.pull-right
													.fa.fa-list-alt{"data-target" => "#modalReportItem-#{resource.id}", "data-toggle" => "modal", type: "button", style: 'cursor:pointer;', title: "Detail report items"}
													.modal.fade{:role => "dialog", id: "modalReportItem-#{resource.id}"}
														= render 'publishers/reports/modal_report_item', resource: resource

		- else
			- if params[:group_by] == 'Campaign'
				.responsive-tabel
					%table#example1.table.table-bordered.table-striped.tabel-width2
						.responsive-content-tabel
							%thead
								%tr
									%th Campaign
									%th Offer
									- unless params[:status] == 'convertion'
										%th
											Clicks
											= button_tag '<i class="fa fa-long-arrow-up" aria-hidden="true"></i>'.html_safe, value: 'sort_by_clicks', class: "btn-up-arrow #{'active' if params[:sort_by] == 'sort_by_clicks'} js-submit-search-report", name: 'sort_by', 'data-toggle'=>"tooltip", 'title'=>"Sort Descending"
										%th
											Visitors
											= button_tag '<i class="fa fa-long-arrow-up" aria-hidden="true"></i>'.html_safe, value: 'sort_by_visitors', class: "btn-up-arrow #{'active' if params[:sort_by] == 'sort_by_visitors'} js-submit-search-report", name: 'sort_by', 'data-toggle'=>"tooltip", 'title'=>"Sort Descending"
										%th
											Unique Visitors
											= button_tag '<i class="fa fa-long-arrow-up" aria-hidden="true"></i>'.html_safe, value: 'sort_by_unique_visitors', class: "btn-up-arrow #{'active' if params[:sort_by] == 'sort_by_unique_visitors'} js-submit-search-report", name: 'sort_by', 'data-toggle'=>"tooltip", 'title'=>"Sort Descending"
									- else
										%th
											Sales
											= button_tag '<i class="fa fa-long-arrow-up" aria-hidden="true"></i>'.html_safe, value: 'sort_by_sales', class: "btn-up-arrow #{'active' if params[:sort_by] == 'sort_by_sales'} js-submit-search-report", name: 'sort_by', 'data-toggle'=>"tooltip", 'title'=>"Sort Descending"
										%th 
											Revenue
											= button_tag '<i class="fa fa-long-arrow-up" aria-hidden="true"></i>'.html_safe, value: 'sort_by_revenue', class: "btn-up-arrow #{'active' if params[:sort_by] == 'sort_by_revenue'} js-submit-search-report", name: 'sort_by', 'data-toggle'=>"tooltip", 'title'=>"Sort Descending"
							%tbody
								- @convertion_reports.each_with_index do |resource|
									- campaign = Campaign.find(resource[0])
									- if current_user.is_admin?
										- link_path = admins_campaign_path(campaign)
									- elsif current_user.is_account_manager?
										- link_path = account_managers_campaign_path(campaign)
									%tr
										%td
											%small
												= link_to campaign.title, link_path
										%td
											%small
												= campaign.category_campaign.name
										- unless params[:status] == 'convertion'
											%td
												%small
													= resource[1]
											%td
												%small
													= resource[2]
											%td
												%small
													= resource[3]
										- else
											%td
												%small
													= resource[4]
											%td
												%small
													= get_currency(resource[5])

			- elsif params[:group_by] == 'Offer'
				.responsive-tabel
					%table#example1.table.table-bordered.table-striped.tabel-width2
						.responsive-content-tabel
							%thead
								%tr
									%th Offer
									- unless params[:status] == 'convertion'
										%th
											Clicks
											= button_tag '<i class="fa fa-long-arrow-up" aria-hidden="true"></i>'.html_safe, value: 'sort_by_clicks', class: "btn-up-arrow #{'active' if params[:sort_by] == 'sort_by_clicks'} js-submit-search-report", name: 'sort_by', 'data-toggle'=>"tooltip", 'title'=>"Sort Descending"
										%th
											Visitors
											= button_tag '<i class="fa fa-long-arrow-up" aria-hidden="true"></i>'.html_safe, value: 'sort_by_visitors', class: "btn-up-arrow #{'active' if params[:sort_by] == 'sort_by_visitors'} js-submit-search-report", name: 'sort_by', 'data-toggle'=>"tooltip", 'title'=>"Sort Descending"
										%th
											Unique Visitors
											= button_tag '<i class="fa fa-long-arrow-up" aria-hidden="true"></i>'.html_safe, value: 'sort_by_unique_visitors', class: "btn-up-arrow #{'active' if params[:sort_by] == 'sort_by_unique_visitors'} js-submit-search-report", name: 'sort_by', 'data-toggle'=>"tooltip", 'title'=>"Sort Descending"
									- else
										%th
											Sales
											= button_tag '<i class="fa fa-long-arrow-up" aria-hidden="true"></i>'.html_safe, value: 'sort_by_sales', class: "btn-up-arrow #{'active' if params[:sort_by] == 'sort_by_sales'} js-submit-search-report", name: 'sort_by', 'data-toggle'=>"tooltip", 'title'=>"Sort Descending"
										%th 
											Revenue
											= button_tag '<i class="fa fa-long-arrow-up" aria-hidden="true"></i>'.html_safe, value: 'sort_by_revenue', class: "btn-up-arrow #{'active' if params[:sort_by] == 'sort_by_revenue'} js-submit-search-report", name: 'sort_by', 'data-toggle'=>"tooltip", 'title'=>"Sort Descending"
							%tbody
								- @convertion_reports.each_with_index do |resource|
									- category_campaign = CategoryCampaign.find(resource[0])
									%tr
										%td
											%small
												= category_campaign.name
										- unless params[:status] == 'convertion'
											%td
												%small
													= resource[1]
											%td
												%small
													= resource[2]
											%td
												%small
													= resource[3]
										- else
											%td
												%small
													= resource[4]
											%td
												%small
													= get_currency(resource[5])

			- elsif params[:group_by] == 'IP Address'
				= render "publishers/campaigns/convertion_reports", subject: "IP Address"

			- elsif params[:group_by] == 'Country'
				= render "publishers/campaigns/convertion_reports", subject: "Country"

			- elsif params[:group_by] == 'Referrer'
				= render "publishers/campaigns/convertion_reports", subject: "Referrer"

			- elsif params[:group_by] == 'Date'
				= render "publishers/campaigns/convertion_reports", subject: "Click Date"

			- elsif params[:group_by] == 'Device'
				= render "publishers/campaigns/convertion_reports", subject: "Device"

			- elsif params[:group_by] == 'Browser'
				= render "publishers/campaigns/convertion_reports", subject: "Browser"

			- elsif params[:group_by] == 'Source'
				= render "publishers/campaigns/convertion_reports", subject: "Source"

			- elsif params[:group_by] == 'Sub1'
				= render "publishers/campaigns/convertion_reports", subject: "Sub1"

			- elsif params[:group_by] == 'Sub2'
				= render "publishers/campaigns/convertion_reports", subject: "Sub2"

		= paginate @convertion_reports, remote: true, param_name: "page_report_convertion"
- else
	= render "shared/empty_blank"

:javascript
	$(document).on('click', '.js-submit-search-report', function(){
		$(".spinner-load").show();
	});

	$(document).on('change', '.js-onchange-group', function(){
		$(".spinner-load").show();
	});
	$('.responsive-tabel').doubleScroll();

app/views/publishers/reports/index.html.haml
= render "publishers/reports/index"