config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: 'confirmations'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  mount Ckeditor::Engine => '/ckeditor'

  root "home#index"
  get 'contact', to: "home#index#contact"
  get 'health-check', to: 'home#health_check'
  get 'about-us', to: 'about_us#index'
  get 'faqs', to: 'faqs#index'
  get 'features', to: 'features#index'
  get 'how-it-works', to: 'how_it_works#index'
  get 'contact', to: 'contacts#index'
  get 'privacy-policy', to: 'privacy_policy#index'
  get 'gdpr-cpaground', to: 'gdpr#index'
  get 'thank_you/:id', to: 'home#thank_you', as: "thank_you"
  get 'waiting_verified/:id', to: 'home#waiting_verified', as: "waiting_verified"
  get 'under-maintenance', to: 'home#under_maintenance', as: 'under_maintenance'
  get '404-not-found', to: 'home#not_found_page', as: 'not_found_page'
  get 'lombok', to: 'home#lombok', as: 'lombok'
  resources :contacts
  resources :subscribers, only: [:create] do 
    collection do
      get :subscribe
      get :unsubscribe
    end
  end

  resources :xhrs do
    collection do
      get :cities
      get :get_box_report
      get :get_balances
      get :get_revenues
      get :get_commisions
      get :get_notifications
      get :get_campaign
      get :get_campaign_date_form
      get :get_offer_cr
      get :get_payment_owners
      get :get_convertion_report
      get :change_convertion_report
    end
  end

  namespace :admins do
    resources :dashboards
    resources :owners
    resources :invoice_owners do
      member do
        put :change_status
      end
    end
    resources :admins
    resources :account_managers do
      member do
        put :change_status
        get :detail_report
      end
      collection do
        get :multiple_action
      end
    end
    resources :publishers do
      member do
        put :change_status
        get :detail_report
      end
      collection do
        get :multiple_action
        get :list_email
      end
    end
    resources :campaigns do
      collection do
        get :multiple_action
        post :import
      end
      member do
        put :change_status
        get :click_notif
      end
    end
    resources :category_campaigns do
      collection do
        get :multiple_action
        get :multiple_action_targeting
        get :multiple_action_banner_image
        post :import
        post :import_per_offer
      end
      member do
        put :change_status
        delete :delete_targeting
        delete :delete_banner_image
      end
    end
    resources :report_campaign_snapshots do
      member do
        put :change_convertion_report
        delete :delete_convertion_report
      end
    end
    resources :contacts
    resources :web_settings
    resources :payment_snapshots do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :layout_themes do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :request_landing_pages do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
        get :click_notif
      end
    end
    resources :subscribers, only: [:index, :show, :destroy] do
      member do
        put :change_status
      end
    end
    resources :blogs do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :forums do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
        delete :delete_comment
      end
    end
    resources :feeds do
      collection do
        post :comment_create
      end
    end
    resources :invoices do
      member do
        put :change_status
      end
    end
    resources :groups do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :access_offers do
      collection do
        get :multiple_action
      end
    end
    resources :reports do
      collection do
        get :input
      end
      member do
        delete :delete_report_item
      end
      collection do
        get :multiple_action
      end
    end
    resources :informations do
      member do
        put :change_status
      end
      collection do
        get :multiple_action
      end
    end
    resources :permission_referral_publishers
    resources :commisions
    resources :payment_commisions do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :messages
  end

  namespace :account_managers do
    resources :dashboards do
      collection do
        resources :rankings
      end
    end
    resources :campaigns do
      member do
        get :click_notif
        put :approvement
      end
    end
    resources :offers
    resources :profiles
    resources :activities
    resources :forums do
      member do
        delete :delete_comment
      end
    end
    resources :blogs do
      collection do
        post :comment_create
      end
    end
    resources :referrals
    resources :payments do
      member do
        get :click_notif
      end
    end
    resources :publishers do
      member do
        get :click_message
        get :detail_report
        put :change_status
        put :suspended
      end
    end
    resources :messages do
      collection do
        post :blast_message
      end
    end
    resources :feeds do
      collection do
        post :comment_create
        post :like_create
      end
    end
    resources :request_landing_pages do
      member do
        get :click_notif
      end
    end
    resources :notifications
    resources :groups do
      member do
        # put :change_status
        put :change_status_group_coverage
        get :click_notif
      end
    end
    resources :offers do
      member do
        get :click_notif
        put :checked
        put :change_status
      end
    end
    resources :reports
    resources :permission_referral_publishers
    resources :commisions
  end

  namespace :publishers do
    # get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :dashboards
    resources :campaigns do
      member do
        get :click_notif
      end
    end
    resources :offers do
      member do
        get :click_notif
        put :checked
        put :change_status
      end
    end
    resources :profiles
    resources :activities
    resources :forums
    resources :blogs do
      collection do
        post :comment_create
      end
    end
    resources :referrals
    resources :payments do
      member do
        get :click_notif
      end
    end
    resources :managers
    resources :messages
    resources :feeds do
      collection do
        post :comment_create
        post :like_create
      end
    end
    resources :request_landing_pages do
      member do
        get :click_notif
        put :change_status
      end
      collection do
        get :download_lp
      end
    end
    resources :notifications
    resources :groups do
      collection do
        post :join
      end
      member do
        get :click_notif
      end
    end
    resources :access_offers
    resources :reports
    resources :referral_publishers
    resources :commisions
    resources :payment_commisions do
      member do
        get :click_notif
      end
    end
    resources :offer_commisions
  end

  namespace :api do
    resources :lp do
      collection do
        get :track_visit
        get :postback
        get :get_campaigns
      end
    end
  end
  get 'postback', to: 'api/lp#postback', as: "postback"
end

app/controllers/account_managers/activities_controller.rb
class AccountManagers::ActivitiesController < AccountManagers::ApplicationController
  before_action :check_profile
  
  add_breadcrumb "dashboard", :account_managers_dashboards_path
  add_breadcrumb "my activities", :account_managers_activities_path

  def index
    @activities = @account_manager.activities.latest.search_by(params).page(page).per(per_page)
  end
  
end

app/controllers/account_managers/application_controller.rb
class AccountManagers::ApplicationController < ApplicationController
  before_action :authenticate_user!

  layout "application_account_manager"
  def authenticate_user!
    unless user_signed_in? && current_user.is_account_manager?
      redirect_to new_user_session_path, alert: "Cannot access this site!"
    else
      @account_manager = AccountManager.find current_user
      @my_publishers = @account_manager.publishers.verified.order(username: :asc)
      ongoing_payment(@account_manager)
      notification
      check_group_message(current_user.id)
    end
  end

  def notification
    @notifications = Notification.sort_unread.latest.where(user_id: @account_manager.id)
  end

  def check_group_message(account_manager_id)
    @group_message = GroupMessage.where(account_manager_id: current_user.id).first

    if @group_message.blank?
      @group_message = GroupMessage.create(account_manager_id: current_user.id, status: 'active')
    end

    if @group_message.present?
      messages = Message.where(to: current_user.id)
      @latest_messages = messages.latest
      latest_messages = messages
      messages_collection = latest_messages.group_by {|m| m.from}
      set_messages_collection = set_collection_message(messages_collection)
      latest_messages_collection = set_messages_collection.sort_by {|e| e[3]}
      @latest_messages_collection = latest_messages_collection.reverse!
    end
  end

  def check_group_message_publisher(account_manager_id, publisher_id)
    @group_message = GroupMessage.where(account_manager_id: current_user.id, publisher_id: publisher_id).first

    if @group_message.blank?
      @group_message = GroupMessage.create(account_manager_id: current_user.id, publisher_id: publisher_id, status: 'active')
    end

    if @group_message.present?
      @publisher_messages = @group_message.messages.oldest
    end
  end

  private
    def set_collection_message(messages)
      messages.values.map{|w| [w.map(&:id).last,
                            w.map(&:from).last,
                            w.map(&:message).last,
                            w.map(&:status).last,
                            w.map(&:created_at).last] 
                          }
    end

end

app/controllers/account_managers/blogs_controller.rb
class AccountManagers::BlogsController < AccountManagers::ApplicationController
  before_action :check_profile
  
  add_breadcrumb "dashboard", :account_managers_dashboards_path
  add_breadcrumb "blogs", :account_managers_blogs_path

  def index
    blogs = Blog.activated
    
    if params[:user].present?
      blogs = Blog.where(user_id: current_user.id)
    else
      blogs = blogs
    end

    @blogs = blogs.latest.page(page).per(per_page)
  end

  def show
    add_breadcrumb "#{params[:action]}"
    resource
    @latest_blogs = Blog.not_in(id: @blog.id).activated.latest.limit(5)
    @blog_comments = @blog.feed_comments.latest.page(page).per(5)

    @blog.update(view_count: @blog.view_count + 1)
  end

  def create
    @blog = Blog.new params_permit
    @blog.user_id = current_user.id
    if @blog.save
      create_activity(@blog, current_user.id, "create blog", "successfully created blog #{@blog.title}")
      redirect_to account_managers_blog_path(@blog), notice: "Successfully created blog"
    else
      redirect_to account_managers_blogs_path, alert: "Unsuccessfully created blog, #{@blog.errors.full_messages.join(',')}"
    end
  end

  def edit
    add_breadcrumb "#{params[:action]}"
    resource
  end

  def update
    resource
    if @blog.update params_permit
      redirect_to account_managers_blog_path(@blog), notice: "Successfully updated blog"
    else
      redirect_to :back, alert: "Unsuccessfully updated blog, #{@blog.errors.full_messages.join(',')}"
    end
  end

  def comment_create
    @feed_comment = FeedComment.create(user_id: current_user.id, message: params[:message], feedable_id: params[:feedable_id], feedable_type: params[:feedable_type])
    
    respond_to do |format|
      format.js { render json: { status: 'Success', user_username: @feed_comment.user.username, user_avatar: @feed_comment.user.avatar.url(:thumb), data: @feed_comment}, status: :ok }
    end
  end

  private
    def resource
      @blog = Blog.find params[:id]
    end

    def params_permit
      params.require(:blog).permit(:title, :description, :category, :attachment_image, :status)
    end
  
end

app/controllers/account_managers/campaigns_controller.rb
class AccountManagers::CampaignsController < AccountManagers::ApplicationController
  before_action :class_name
  before_action :check_profile

  add_breadcrumb "dashboard", :account_managers_dashboards_path
  add_breadcrumb "publisher campaigns", :account_managers_campaigns_path

  def index
    @campaigns = collection.page(page).per(per_page)
  end

  def show
    add_breadcrumb "#{params[:action]}"
    resource
    redirect_to :back, alert: "You can not enter this page, your Campaign '#{@campaign.title}' is still not approved" unless @campaign.is_active? || @campaign.is_complete?
    @landing_pages = @campaign.request_landing_pages.latest.page(params[:page_landing_pages]).per(per_page) if @campaign.request_landing_pages.present?
    
    get_analytic_report(@campaign.publisher, 'dashboard_am_campaign')
    @offer = @campaign.category_campaign
    @banner_images = @campaign.category_campaign.banner_images
    
    if @convertion_reports.present?
      set_collection_convertion_report(params[:group_by], @convertion_reports, "publisher")
      # multipe_chart(@convertion_reports_list)
    end
    
    respond_to do |format|
      format.html 
      format.xls
      format.js
    end
  end

  def click_notif
    notification = Notification.find(params[:notification_id])
    notification.status = "read"
    notification.save

    redirect_to account_managers_campaign_path(params[:id])
  end

  def approvement
    resource
    @campaign.status = Campaign::ACTIVE
    if @campaign.save
      UserMailer.after_update_campaign(@campaign).deliver_now!
      create_activity(@campaign, current_user.id, "change status #{@resource_name.downcase} to #{@campaign.status}", "successfully changed #{@resource_name.downcase} #{@campaign.title}")
      create_activity(@account_manager, current_user.id, "change status #{@resource_name.downcase} to #{@campaign.status}", "successfully changed #{@resource_name.downcase} #{@campaign.title}")
      create_notification(@campaign, @campaign.publisher_id, "Your #{@resource_name.downcase} #{@campaign.title}", "Your #{@resource_name.downcase} #{@campaign.title} has approved.")
      create_notification(@campaign, @campaign.admin_id, "#{@campaign.publisher.username.capitalize} #{@resource_name.downcase} #{@campaign.title}", "#{@campaign.publisher.username.capitalize} #{@resource_name.downcase} #{@campaign.title} has approved by #{@campaign.account_manager.username}.")
    else
    end

    respond_to do |format|
      format.js { render json: { status: 'Success', data: @campaign }, status: :ok }
    end
  end

  private
    def resource
      @campaign = @account_manager.campaigns.find(params[:id])
    end

    def collection
      @campaigns = @account_manager.campaigns.latest.search_by(params)
    end

    def class_name
      @resource_name = 'Campaign'
      @collection_name = 'Campaigns'
    end
end

app/controllers/account_managers/commisions_controller.rb
class AccountManagers::CommisionsController < AccountManagers::ApplicationController
	before_action :check_profile
	before_action :class_name
	
	add_breadcrumb "dashboard", :account_managers_dashboards_path
	add_breadcrumb "publishers commisions", :account_managers_commisions_path

	def index
		collection
		@total_collection = @commisions.count rescue 0
		@fee_approved = @commisions.approved.sum(:fee_publisher)
		@fee_pending = @commisions.pending.sum(:fee_publisher)
		@fee_rejected = @commisions.rejected.sum(:fee_publisher)
		query_last_next_payment_commisions(@commisions)
		commisions = @commisions.where(status: "approved")
		@commision_today_so_far = commisions.where(campaign_date: @date).sum(:fee_publisher) rescue 0
		@commision_yesterday = commisions.where(campaign_date: @date.yesterday).sum(:fee_publisher) rescue 0
		@commision_last_7_month = commisions.where(:campaign_date.gte => @date - 6.days, :campaign_date.lte => @date).sum(:fee_publisher) rescue 0
		@commision_this_month = commisions.where(:campaign_date.gte => @date.beginning_of_month, :campaign_date.lte => @date.end_of_month).sum(:fee_publisher) rescue 0
		
		unless params[:start_at].present? && params[:end_at].present?
			if commisions.present?
				@commisions = commisions.where(:campaign_date.gte => @date).where(:campaign_date.lte => @date)
			end
		else
			@commisions = commisions
		end

		@commisions_group = @commisions.group_by {|d| d.campaign_date} rescue nil 

		@commisions = @commisions.page(params[:page_commisions]).per(per_page) rescue nil
	end

	private
		def collection
			@commisions = @account_manager.commisions.search_by(params)
		end

		def class_name
			@resource_name = 'Publisher Commisions'
			@collection_name = 'Publishers Commisions'
		end
end

app/views/admins/account_managers/_list_activities.html.haml
#wallmessages.qa-message-list
  - @activities.each do |resource|
    .message-item
      .message-inner
        .message-head.clearfix
          .avatar.pull-left
            = link_to admins_account_manager_path(resource.account_manager) do
              .avatar-timeline
                = image_tag resource.account_manager.avatar
          .user-detail.timeline-m
            %h5.handle
              = resource.name
            .post-meta
              .asker-meta.text-left-m
                %span.qa-message-what
                %span.qa-message-when
                  %span.qa-message-when-data= get_datetime(resource.created_at)
                %br.mobile
                %span.qa-message-who
                  %span.qa-message-who-pad by
                  %span.qa-message-who-data
                    = link_to "#{resource.account_manager.username}", admins_account_manager_path(resource.account_manager)
        .qa-message-content
          = resource.description
= paginate @activities, remote: true, param_name: "page_activities"

app/views/admins/account_managers/_list_payment_snapshots.html.haml
.responsive-tabel
  .responsive-content-tabel
    %table#example1.table.table-bordered.table-striped.tabel-width2
      %thead
        %tr
          %th No.
          %th Invoice
          %th Revenue Publisher
          %th Fee AM
          %th Fee Company
          %th Total
          %th Payment at
          %th Payment end
          %th Created At
          %th{width: '80'} Action
      %tbody
        - if @payment_snapshots.blank?
          %tr
            %td{ colspan: "12"}
              %center Data not found.
        - else
          - @payment_snapshots.each_with_index do |resource, index|  
            %tr
              %td
                = index+1
              %td
                = resource.code
              %td
                = get_currency(resource.price)
              %td
                = get_currency(resource.fee_am)
              %td
                = get_currency(resource.fee_company)
              %td
                = get_currency(resource.total)
              %td
                = date_sort_time(resource.payment_at)
              %td
                = date_sort_time(resource.payment_end)
              %td
                = get_datetime(resource.created_at)
              %td
                = link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, admins_payment_snapshot_path(resource), class: 'btn btn-default btn-xs'
                = link_to '<i class="fa fa-wrench" aria-hidden="true"></i>'.html_safe, edit_admins_payment_snapshot_path(resource), class: 'btn btn-default btn-xs' if current_user.is_admin?
= paginate @payment_snapshots, remote: true, param_name: "page_payment_snapshots"

app/views/admins/account_managers/_list_request_landing_pages.html.haml
.responsive-tabel
  .responsive-content-tabel
    %table#example1.table.table-bordered.table-striped.tabel-width1
      %thead
        %tr
          %th Code
          %th Category Name
          %th Campaign
          %th Publisher
          %th Layout Theme
          %th Domain
          %th Status
          %th Created At
          %th{width: '50px'} Action
      %tbody
        - if @request_landing_pages.blank?
          %tr
            %td{ colspan: "8"} 
              = render "shared/empty_blank"
        - else
          - @request_landing_pages.each_with_index do |resource, index|  
            %tr
              %td
                = resource.code
              %td
                = resource.category[:name]
              %td
                = link_to resource.campaign.title, admins_campaign_path(resource.campaign)
              %td
                = link_to resource.publisher.username, admins_publisher_path(resource.publisher)
              %td
                = resource.try(:layout_theme).try(:title)
              %td
                = resource.domain ? resource.domain : "---"
              %td
                = resource.status?
              %td
                = get_datetime(resource.created_at)
              %td
                = link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, admins_request_landing_page_path(resource), class: 'btn btn-default btn-xs'
= paginate @request_landing_pages, remote: true, param_name: "page_landing_pages"

app/views/admins/account_managers/_sales.html.haml
= render 'shared/loading'
.panel.hpanel.responsive-hpanel
  .panel-body
    %h4{align: 'center'} TOP MANAGER BY SALES
    %br
    = form_for :search, url: admins_account_managers_path, method: 'get', html: {class: 'form-search2', remote: true} do
      .col-md-2.col-md-offset-4
        = text_field_tag :campaign_start_at, params[:campaign_start_at].blank? ? @date.beginning_of_month : params[:campaign_start_at], class: 'form-control datepicker campaign_start_at', placeholder: 'Campaign Start At'
      .col-md-2
        = text_field_tag :campaign_end_at, params[:campaign_end_at].blank? ? @date : params[:campaign_end_at], class: 'form-control datepicker campaign_end_at',  placeholder: 'Campaign End At'
    = bar_chart @sales_am

:javascript
  $(document).ready(function(){
    $('.datepicker').datepicker({
      format: "yyyy-mm-dd",
      autoclose: true
    });
  });

app/views/admins/account_managers/detail_report.html.haml
/ Main Wrapper
#wrapper.detail-report
  .normalheader.top-header
    .panel
      .panel-body
        #hbreadcrumb.pull-right.m-t-lg.breadcrumb-capital
          %ol.breadcrumb.hbreadcrumb
            = render_breadcrumbs :tag => :li, :separator => ""
        %h2.font-light.m-b-xs
          %b #{@account_manager.username.titleize} Report Campaigns
        %p 
          This report is all #{@account_manager.username.titleize}'s belongs. 
          = link_to "Back to detail account_manager", admins_account_manager_path(@account_manager)
  .content.full-page.top-min
    .row
      .count-total
        .col-md-9
          .box.box-m.box-default.estimate-earnings
            .box-footer
              .row
                .col-md-12
                  %h3 Estimated Earnings
                .col-xs-3
                  .description-block
                    %h3.text-success
                      = get_currency(@earning_today_so_far)
                    %small Today so far    
                .col-xs-3
                  .description-block
                    %h3.text-success
                      = get_currency(@earning_yesterday)
                    %small Yesterday
                .col-xs-3
                  .description-block
                    %h3.text-success
                      = get_currency(@earning_last_7_month)
                    %small Last 7 days
                .col-xs-3
                  .description-block
                    %h3.text-success
                      = get_currency(@earning_this_month)
                    %small This month
                
        .col-md-3
          .box.box-m.box-default.estimate-earnings
            .box-footer
              .row
                .col-md-12
                  %h3 Balance
                .col-md-12
                  %h3.text-success 
                    = get_currency(@_last_payment)
                  %small Last Payment

      .col-lg-12.m-t-md.content-campaign
        %ul.nav.nav-tabs
          %li
            %a{"aria-expanded" => "false", "data-toggle" => "tab", :href => "#tab-1"} 
              %i.fa.fa-table
              &nbsp; Reports Convertion
          %li.active
            %a{"aria-expanded" => "true", "data-toggle" => "tab", :href => "#tab-2"} 
              %i.fa.fa-line-chart
              &nbsp; Analytic Campaign

        = form_for :select_date, url: detail_report_admins_account_manager_path(@account_manager), method: 'get', remote: true, html: {class: 'js-form-submit'} do
          .tab-content.no-padding-m.background-white
            #tab-1.tab-pane
              .panel-body
                #table-list-report_campaign_snapshots
                  = render 'publishers/campaigns/am_list_report_campaign_snapshots', report_campaign_snapshots: @report_campaign_snapshots, report_for: 'account_manager'

            #tab-2.tab-pane.active
              .panel-body.responsive-panel-analytic
                .row.responsive-row-analytic
                  .col-xs-6
                    .simple-search
                      .input-group.js-field-search
                        = render 'shared/analytics/field_search'
                  .col-xs-6
                    #btn-group-analytic
                      = render 'admins/campaigns/btn_group_analytic'
                  .col-xs-12
                    .btn-group.pull-right.btn-chart
                      %button.btn.btn-default.btn-total-revenue
                        Total Earnings :
                        %span.total-revenue #{get_currency(@reports_total_revenue)}
                  .col-xs-12
                    #the-report-analytics
                      = render "shared/analytics/analytic", report_for: 'account_manager'

app/views/admins/account_managers/edit.html.haml
= render "shared/admin/breadcrumbs"

%section.content.full-page
  .row
    .col-md-12
      .box.box-m
        .box-header
          %h3.box-title
            = @collection_name
          = link_to 'Back To List', admins_account_managers_path, class: 'btn btn-info btn-xs pull-right'
          %hr
        .box-body
          = form_for @account_manager, url: admins_account_manager_path, method: 'put', html: { multipart:true } do |f|
            = render 'form', f: f
            = submit_tag "Update", class: "btn btn-info"
        .content-footer

app/views/admins/account_managers/index.html.haml
#breadcrumbs
  = render "shared/admin/breadcrumbs"
= render 'shared/loading'
%section.content.full-page
  .row
    .bg-white
      .col-md-12.search
        / .row
        /   .col-xs-12
        /     #js-sales-am
        /       = render 'admins/account_managers/sales'
        
        .row.top-plus
          .col-xs-12
            .box.box-m
              .box-body
                .exTab
                  .scroll-tab
                    %ul.nav.nav-tabs
                      %li.active
                        %a{"data-toggle" => "tab", :href => "#1"} Lists
                      %li
                        %a{"data-toggle" => "tab", :href => "#2"} Ranking Managers
                  .tab-content.background-white
                    #1.tab-pane.active
                      = form_for :search, url: admins_account_managers_path, method: 'get', html: {class: 'form-search', remote: true} do
                        .input-group.full
                          .col-md-3.no-padding
                            = text_field_tag :key, params[:key], class: 'form-control pull-right radius-left', placeholder: 'Keywords'
                          .col-md-2.no-padding
                            = select_tag :status, options_for_select([["All Status", ""], ["Inactive", false], ["Active", true]], params[:status]), class: 'form-control'
                          .col-md-3.no-padding
                            = text_field_tag :start_at, nil, value: params[:start_at], class: 'form-control datepicker', placeholder: 'Start At'
                          .col-md-3.no-padding
                            = text_field_tag :end_at, nil, value: params[:end_at], class: 'form-control datepicker',  placeholder: 'End At'
                          .col-md-1.no-padding
                            = submit_tag :Search, class: 'btn btn-info radius-right js-btn-submit'
                            
                      #table-lists
                        = render 'admins/account_managers/lists'
                    #2.tab-pane
                      = form_for :search, url: admins_account_managers_path, method: 'get', html: {class: 'form-search2', remote: true} do
                        .input-group.full
                          .col-md-5.no-padding
                            = text_field_tag :campaign_start_at, params[:campaign_start_at].blank? ? @date.beginning_of_month : params[:campaign_start_at], class: 'form-control datepicker campaign_start_at', placeholder: 'Campaign Start At'
                          .col-md-5.no-padding
                            = text_field_tag :campaign_end_at, params[:campaign_end_at].blank? ? @date : params[:campaign_end_at], class: 'form-control datepicker',  placeholder: 'Campaign End At'
                          .col-md-2.no-padding
                            = submit_tag :Search, class: 'btn btn-info radius-right js-btn-submit2'

                      #js-table-ranking-am 
                        = render 'admins/account_managers/ranking_am'

:javascript
  $(document).ready(function() {
    $(document).on('click', '.js-btn-submit', function(){
      $('.form-search').trigger('submit.rails');
      $(".spinner-load").show();
    });

    $(document).on('click', '.js-btn-submit2', function(){
      $('.form-search2').trigger('submit.rails');
      $(".spinner-load").show();
    });
  });

app/views/admins/account_managers/index.js.erb
$('#breadcrumbs').html("<%= escape_javascript render partial: 'shared/admin/breadcrumbs' %>");
$('#table-lists').html("<%= escape_javascript render 'lists' %>");
$('#js-sales-am').html("<%= escape_javascript render 'sales' %>");
$('#js-table-ranking-am').html("<%= escape_javascript render 'ranking_am' %>");

$(document).ready(function() {
  $(".spinner-load").fadeOut(1000);
});

app/views/admins/account_managers/new.html.haml
= render "shared/admin/breadcrumbs"

%section.content.full-page
  .row  
    .col-md-12
      .box.box-m
        .box-header
          %b
            = @collection_name
            = link_to 'Back To List', admins_account_managers_path, class: 'btn btn-info btn-xs pull-right'
          %hr
        .box-body
          = form_for @account_manager, url: admins_account_managers_path, method: 'post', html: { multipart:true } do |f|
            = render 'form', f: f
            = submit_tag "Create", class: "btn btn-info"
        .content-footer