config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: 'confirmations'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  mount Ckeditor::Engine => '/ckeditor'

  root "home#index"
  get 'contact', to: "home#index#contact"
  get 'health-check', to: 'home#health_check'
  get 'about-us', to: 'about_us#index'
  get 'faqs', to: 'faqs#index'
  get 'features', to: 'features#index'
  get 'how-it-works', to: 'how_it_works#index'
  get 'contact', to: 'contacts#index'
  get 'privacy-policy', to: 'privacy_policy#index'
  get 'gdpr-cpaground', to: 'gdpr#index'
  get 'thank_you/:id', to: 'home#thank_you', as: "thank_you"
  get 'waiting_verified/:id', to: 'home#waiting_verified', as: "waiting_verified"
  get 'under-maintenance', to: 'home#under_maintenance', as: 'under_maintenance'
  get '404-not-found', to: 'home#not_found_page', as: 'not_found_page'
  get 'lombok', to: 'home#lombok', as: 'lombok'
  resources :contacts
  resources :subscribers, only: [:create] do 
    collection do
      get :subscribe
      get :unsubscribe
    end
  end

  resources :xhrs do
    collection do
      get :cities
      get :get_box_report
      get :get_balances
      get :get_revenues
      get :get_commisions
      get :get_notifications
      get :get_campaign
      get :get_campaign_date_form
      get :get_offer_cr
      get :get_payment_owners
      get :get_convertion_report
      get :change_convertion_report
    end
  end

  namespace :admins do
    resources :dashboards
    resources :owners
    resources :invoice_owners do
      member do
        put :change_status
      end
    end
    resources :admins
    resources :account_managers do
      member do
        put :change_status
        get :detail_report
      end
      collection do
        get :multiple_action
      end
    end
    resources :publishers do
      member do
        put :change_status
        get :detail_report
      end
      collection do
        get :multiple_action
        get :list_email
      end
    end
    resources :campaigns do
      collection do
        get :multiple_action
        post :import
      end
      member do
        put :change_status
        get :click_notif
      end
    end
    resources :category_campaigns do
      collection do
        get :multiple_action
        get :multiple_action_targeting
        get :multiple_action_banner_image
        post :import
        post :import_per_offer
      end
      member do
        put :change_status
        delete :delete_targeting
        delete :delete_banner_image
      end
    end
    resources :report_campaign_snapshots do
      member do
        put :change_convertion_report
        delete :delete_convertion_report
      end
    end
    resources :contacts
    resources :web_settings
    resources :payment_snapshots do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :layout_themes do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :request_landing_pages do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
        get :click_notif
      end
    end
    resources :subscribers, only: [:index, :show, :destroy] do
      member do
        put :change_status
      end
    end
    resources :blogs do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :forums do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
        delete :delete_comment
      end
    end
    resources :feeds do
      collection do
        post :comment_create
      end
    end
    resources :invoices do
      member do
        put :change_status
      end
    end
    resources :groups do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :access_offers do
      collection do
        get :multiple_action
      end
    end
    resources :reports do
      collection do
        get :input
      end
      member do
        delete :delete_report_item
      end
      collection do
        get :multiple_action
      end
    end
    resources :informations do
      member do
        put :change_status
      end
      collection do
        get :multiple_action
      end
    end
    resources :permission_referral_publishers
    resources :commisions
    resources :payment_commisions do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :messages
  end

  namespace :account_managers do
    resources :dashboards do
      collection do
        resources :rankings
      end
    end
    resources :campaigns do
      member do
        get :click_notif
        put :approvement
      end
    end
    resources :offers
    resources :profiles
    resources :activities
    resources :forums do
      member do
        delete :delete_comment
      end
    end
    resources :blogs do
      collection do
        post :comment_create
      end
    end
    resources :referrals
    resources :payments do
      member do
        get :click_notif
      end
    end
    resources :publishers do
      member do
        get :click_message
        get :detail_report
        put :change_status
        put :suspended
      end
    end
    resources :messages do
      collection do
        post :blast_message
      end
    end
    resources :feeds do
      collection do
        post :comment_create
        post :like_create
      end
    end
    resources :request_landing_pages do
      member do
        get :click_notif
      end
    end
    resources :notifications
    resources :groups do
      member do
        # put :change_status
        put :change_status_group_coverage
        get :click_notif
      end
    end
    resources :offers do
      member do
        get :click_notif
        put :checked
        put :change_status
      end
    end
    resources :reports
    resources :permission_referral_publishers
    resources :commisions
  end

  namespace :publishers do
    # get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :dashboards
    resources :campaigns do
      member do
        get :click_notif
      end
    end
    resources :offers do
      member do
        get :click_notif
        put :checked
        put :change_status
      end
    end
    resources :profiles
    resources :activities
    resources :forums
    resources :blogs do
      collection do
        post :comment_create
      end
    end
    resources :referrals
    resources :payments do
      member do
        get :click_notif
      end
    end
    resources :managers
    resources :messages
    resources :feeds do
      collection do
        post :comment_create
        post :like_create
      end
    end
    resources :request_landing_pages do
      member do
        get :click_notif
        put :change_status
      end
      collection do
        get :download_lp
      end
    end
    resources :notifications
    resources :groups do
      collection do
        post :join
      end
      member do
        get :click_notif
      end
    end
    resources :access_offers
    resources :reports
    resources :referral_publishers
    resources :commisions
    resources :payment_commisions do
      member do
        get :click_notif
      end
    end
    resources :offer_commisions
  end

  namespace :api do
    resources :lp do
      collection do
        get :track_visit
        get :postback
        get :get_campaigns
      end
    end
  end
  get 'postback', to: 'api/lp#postback', as: "postback"
end

app/views/admins/admins/_form.html.haml
.row
	.col-md-12
		- if current_user.is_admin?
			.form-group
				= f.label "Role"
				= f.select :role_id, options_for_select([['Staff', User::STAFF_ROLE], ['Finance', User::FINANCE_ROLE]], @admin.role_id), {prompt: 'Choice Role'}, class: 'form-control', disabled: params[:action] == 'edit' ? true : false
	.col-md-6
		.form-group
			= f.label :username
			= f.text_field :username, placeholder: "Enter username", class: 'form-control', required: true
	.col-md-6
		.form-group
			= f.label :email
			= f.email_field :email, placeholder: "Enter email", class: 'form-control', required: true
	.col-md-6
		.form-group
			= f.label :phone
			.row
				.col-xs-5
					.no-right
						= f.select :phone_code, get_phone_codes, {prompt: 'Code'}, class: 'form-control', required: true
				.col-xs-7
					= f.text_field :phone, placeholder: "Phone Number", class: 'form-control', required: true
	.col-md-6
		.form-group
			= f.label :skype
			= f.text_field :skype, placeholder: "Enter skype", class: 'form-control', required: true
	- if current_user.is_admin?
		- if @admin != current_user
			.col-md-12
				.form-group
					= f.label :status
					= f.select :verified, [['Inactive', false], ['Active', true]], {prompt: 'Select Status'}, class: 'form-control', required: true
	.col-md-6
		.form-group
			= f.label :password
			= f.password_field :password, placeholder: "Enter password", class: 'form-control'
	.col-md-6
		.form-group
			= f.label :password_confirmation
			= f.password_field :password_confirmation, placeholder: "Enter password confirmation", class: 'form-control'

app/views/admins/admins/_list_activities.html.haml
#wallmessages.qa-message-list
  - @activities.each do |resource|
    .message-item
      .message-inner
        .message-head.clearfix
          .avatar.pull-left
            = link_to admins_admin_path(resource.admin) do
              .avatar-timeline
                = image_tag resource.admin.avatar
          .user-detail.timeline-m
            %h5.handle
              = resource.name
            .post-meta
              .asker-meta.text-left-m
                %span.qa-message-what
                %span.qa-message-when
                  %span.qa-message-when-data= get_datetime(resource.created_at)
                %br.mobile
                %span.qa-message-who
                  %span.qa-message-who-pad by &nbsp;
                  %span.qa-message-who-data
                    = link_to "#{resource.admin.username}", admins_admin_path(resource.admin)
        .qa-message-content
          = resource.description
= paginate @activities, remote: true, param_name: "page_activities"

app/views/admins/admins/_list_campaigns.html.haml
.responsive-tabel
  .responsive-content-tabel
    %table#example1.table.table-bordered.table-striped.tabel-width1
      %thead
        %tr
          %th No.
          %th Code
          %th Publisher
          %th AM
          %th Title
          %th Link
          %th Link Campaign
          %th Status
          %th Created At
          %th{width: '70px'} Action
      %tbody
        - if @campaigns.blank?
          %tr
            %td{ colspan: "10"}
              %center Data not found.
        - else
          - @campaigns.each_with_index do |resource, index|  
            %tr
              %td
                = index+1
              %td
                = resource.code
              %td
                - if resource.publisher.present?
                  = link_to resource.try(:publisher).try(:username), admins_publisher_path(resource.try(:publisher))
                - else
                  = "---"
              %td
                = link_to resource.try(:account_manager).try(:username), admins_account_manager_path(resource.try(:account_manager))
              %td
                = resource.title
              %td
                = resource.link
              %td
                = resource.tracking_code
              %td
                = resource.status?
              %td
                = get_datetime(resource.created_at)
              %td
                = link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, admins_campaign_path(resource), class: 'btn btn-default btn-xs'
                = link_to '<i class="fa fa-wrench" aria-hidden="true"></i>'.html_safe, edit_admins_campaign_path(resource), class: 'btn btn-default btn-xs'
= paginate @campaigns, remote: true, param_name: "page_campaigns"

app/views/admins/admins/_list_payment_snapshots.html.haml
.responsive-tabel
  .responsive-content-tabel
    %table#example1.table.table-bordered.table-striped.tabel-width2
      %thead
        %tr
          %th No.
          %th Invoice
          %th Publisher
          %th AM
          %th{ width: "100px"} Earnings Publisher
          %th Fee AM
          %th Fee Company
          %th Total
          %th Payment at
          %th Payment end
          %th Created At
          %th Action
      %tbody
        - if @payment_snapshots.blank?
          %tr
            %td{ colspan: "12"}
              %center Data not found.
        - else
          - @payment_snapshots.each_with_index do |resource, index|  
            %tr
              %td
                = index+1
              %td
                = resource.code
              %td
                = link_to resource.try(:publisher).try(:username), admins_publisher_path(resource.try(:publisher))
              %td
                = link_to resource.try(:account_manager).try(:username), admins_account_manager_path(resource.try(:account_manager))
              %td
                = get_currency(resource.price)
              %td
                = get_currency(resource.fee_am)
              %td
                = get_currency(resource.fee_company)
              %td
                = get_currency(resource.total)
              %td
                = date_sort_time(resource.payment_at)
              %td
                = date_sort_time(resource.payment_end)
              %td
                = get_datetime(resource.created_at)
              %td
                = link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, admins_payment_snapshot_path(resource), class: 'btn btn-default btn-xs'
                = link_to '<i class="fa fa-wrench" aria-hidden="true"></i>'.html_safe, edit_admins_payment_snapshot_path(resource), class: 'btn btn-default btn-xs'
= paginate @payment_snapshots, remote: true, param_name: "page_payment_snapshots"

app/views/admins/admins/_list_report_campaign_snapshots.html.haml
.responsive-tabel
  .responsive-content-tabel
    %table#example1.table.table-bordered.table-striped.tabel-width1
      %thead
        %tr
          %th Date
          %th Code
          %th Publisher
          %th Impressions
          %th Clicks
          %th Visitors
          %th Unique Visitors
          %th Sales
          %th Revenue
          %th Created At
          %th{width: '70px'} Action
      %tbody
        - @report_campaign_snapshots.each_with_index do |resource, index|  
          %tr
            %td
              = resource.campaign_date
            %td
              = resource.code
            %td
              = link_to resource.publisher.username, admins_publisher_path(resource.publisher)
            %td
              = resource.impressions
            %td
              = resource.clicks
            %td
              = resource.visitors
            %td
              = resource.unique_visitors
            %td
              = resource.sales
            %td
              = get_currency(resource.revenue)
            %td
              = get_datetime(resource.created_at)
            %td
              = link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, admins_report_campaign_snapshot_path(resource), class: 'btn btn-default btn-xs'
              = link_to '<i class="fa fa-wrench" aria-hidden="true"></i>'.html_safe, edit_admins_report_campaign_snapshot_path(resource), class: 'btn btn-default btn-xs'
= paginate @report_campaign_snapshots, remote: true, param_name: "page_report_campaign_snapshots"

app/views/admins/admins/_list_verification_snapshots.html.haml
.responsive-tabel
  .responsive-content-tabel
    %table#example1.table.table-bordered.table-striped.tabel-width2
      %thead
        %tr
          %th No.
          %th Publisher
          %th Account Manager
          %th Message
          %th Status
          %th Created At
          %th{width: '70px'} Action
      %tbody
        - @verification_snapshots.each_with_index do |resource, index|  
          %tr
            %td
              = index+1
            %td
              = link_to resource.try(:publisher).try(:username), admins_publisher_path(resource.publisher)
            %td
              = link_to resource.try(:account_manager).try(:username), admins_account_manager_path(resource.account_manager)
            %td
              = resource.message
            %td
              = resource.status?
            %td
              = get_datetime(resource.created_at)
            %td
              = link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, admins_publisher_path(resource.publisher), class: 'btn btn-default btn-xs'
              = link_to '<i class="fa fa-wrench" aria-hidden="true"></i>'.html_safe, edit_admins_publisher_path(resource.publisher), class: 'btn btn-default btn-xs'
= paginate @verification_snapshots, remote: true, param_name: "page_verification_snapshots"

app/views/admins/admins/_lists.html.haml
= link_to new_admins_admin_path, class: 'btn btn-info btn-sm pull-left' do
  %i.fa.fa-user
  &nbsp; Create Admin

%a{ href: "admins.xls?#{request.fullpath.split("?")[1]}", class: 'btn  btn-success btn-sm pull-right'}
  %i.fa.fa-file-excel-o
  &nbsp;
  Export to excel

.full.responsive-tabel
  .responsive-content-tabel
    %table.table.table-hover.table-striped.table-bordered.tabel-width
      %thead
        %tr
          %th Username
          %th{width: '25%'} Email
          %th Type
          %th Status
          %th Created At
          %th{width: '75px'} Action
      %tbody
        - if @admins.blank?
          %tr
            %td{ colspan: "6"} 
              = render "shared/empty_blank"
        - else
          - @admins.each do |resource|
            %tr
              %td
                = resource.username
              %td
                = resource.email
              %td
                = resource.role_id == User::STAFF_ROLE ? 'Staff' : 'Finance'
              %td
                = resource.status?
              %td
                = resource.created_at.strftime("%I:%M %B, %d, %Y")
              %th.text-center
                = link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, admins_admin_path(resource), class: 'btn btn-default btn-xs' unless resource.is_finance?
                &nbsp;
                = link_to '<i class="fa fa-wrench" aria-hidden="true"></i>'.html_safe, edit_admins_admin_path(resource), class: 'btn btn-default btn-xs'
= paginate @admins, remote: true

app/views/admins/admins/edit.html.haml
= render "shared/admin/breadcrumbs"

%section.content.full-page
  .row
    .col-md-12
      .box.box-m
        .box-header
          %b
            = @collection_name
            = link_to 'Back To List', admins_admins_path, class: 'btn btn-info btn-xs pull-right' if current_user.is_admin?
          %hr
        .box-body
          = form_for @admin, url: admins_admin_path, method: 'put' do |f|
            = render 'form', f: f
            = submit_tag "Update", class: "btn btn-info"

app/views/admins/admins/index.html.haml
#breadcrumbs
  = render "shared/admin/breadcrumbs"

%section.content.full-page
  .row
    .bg-white
      .col-md-12.search
        = form_for :search, url: admins_admins_path, method: 'get', html: {class: 'form-search', remote: true} do
          .input-group.full
            .col-md-3.no-padding
              = text_field_tag :key, params[:key], class: 'form-control pull-right radius-left', placeholder: 'Keywords'
            .col-md-2.no-padding
              = select_tag :status, options_for_select([["All Status", ""], ["Inactive", false], ["Active", true]], params[:status]), class: 'form-control'
            .col-md-3.no-padding
              = text_field_tag :start_at, nil, value: params[:start_at], class: 'form-control datepicker', placeholder: 'Start At'
            .col-md-3.no-padding
              = text_field_tag :end_at, nil, value: params[:end_at], class: 'form-control datepicker',  placeholder: 'End At'
            .col-md-1.no-padding
              = submit_tag :Search, class: 'btn btn-info radius-right'
  .row
    .col-xs-12.top-plus
      .box.box-m
        .box-body.responsive-content-tabel
          #table-lists
            = render 'admins/admins/lists'

app/views/admins/admins/index.js.erb
$('#breadcrumbs').html("<%= escape_javascript render partial: 'shared/admin/breadcrumbs' %>");
$('#table-lists').html("<%= escape_javascript render partial: 'lists', locals: {admins: @admins} %>");

app/views/admins/admins/index.xls.erb
<table border="1">
  <caption>LIST ADMINS</caption>
  <tr>
    <th>No</th>
    <th>Username</th>
    <th>Email</th>
    <th>Type</th>
    <th>Status</th>
    <th>Created at</th>
  </tr>
  <% @admins.each_with_index do |resource, index| %>
  <tr>
    <td><%= index+1 %></td>
    <td><%= resource.try(:username) %></td>
    <td><%= resource.try(:email) %></td>
    <td><%= resource.role_id == User::STAFF_ROLE ? 'Staff' : 'Finance' %></td>
    <td><%= resource.status? %></td>
    <td><%= resource.created_at.strftime("%I:%M %B, %d, %Y") %></td>
  </tr>
  <% end %>
</table>

app/views/admins/admins/new.html.haml
= render "shared/admin/breadcrumbs"

%section.content.full-page
  .row
    .col-md-12
      .box.box-m
        .box-header
          %b
            = @collection_name
            = link_to 'Back To List', admins_admins_path, class: 'btn btn-info btn-xs pull-right'
          %hr
        .box-body
          = form_for @admin, url: admins_admins_path, method: 'post' do |f|
            = render 'form', f: f
            = submit_tag "Create", class: "btn btn-info"

app/views/admins/admins/show.html.haml
= render "shared/admin/breadcrumbs"
	
%section.content.full-page.tab-content.tab-content
	.row
		.col-xs-12
			.box.box-m
				.box-header
					%h3.box-title
						Data #{@admin.class.name}
					.pull-right
						= link_to '<i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Back'.html_safe, admins_admins_path, class: "btn btn-info btn-xs"
						&nbsp;
						= link_to '<i class="fa fa-wrench" aria-hidden="true"></i> Edit'.html_safe, edit_admins_admin_path(@admin), class: "btn btn-default btn-xs"
					%hr
				.box-body
					.show-admin
						.col-md-2
							.photo-profile
								= image_tag @admin.avatar
						.col-md-6.no-padding-m
							.row
								.col-md-3
									.form-group
										%b Username
								.col-md-9
									.form-group 
										= @admin.username
								.col-md-3
									.form-group
										%b Email
								.col-md-9
									.form-group 
										= @admin.email
								.col-md-3
									.form-group
										%b Phone
								.col-md-9
									.form-group 
										= @admin.get_phone_number || "---"
								.col-md-3
									.form-group
										%b Skype
								.col-md-9
									.form-group 
										= @admin.skype
								.col-md-3
									.form-group
										%b Status
								.col-md-9
									.form-group 
										= @admin.status?
								.col-md-3
									.form-group
										%b Created at
								.col-md-9
									.form-group 
										= get_datetime(@admin.created_at)
						.col-md-4
							- if @admin.verified == false
								%h4 Activate this account?
								= form_for @admin, url: admins_admin_path, method: 'put' do |f|
									= f.hidden_field :verified, value: true
									= f.submit "Activated", class: 'btn btn-success btn-xs'
						.col-md-12.tab-responsive
							.exTab
								.scroll-tab
									%ul.nav.nav-tabs
										%li.active
											%a{"data-toggle" => "tab", :href => "#1"} Payment Histories
										%li
											%a{"data-toggle" => "tab", :href => "#2"} Campaigns
										%li
											%a{"data-toggle" => "tab", :href => "#3"} Report campaign Snapshots
										%li
											%a{"data-toggle" => "tab", :href => "#4"} Verification Stories
										%li
											%a{"data-toggle" => "tab", :href => "#5"} Activities
								.tab-content
									#1.tab-pane.active
										- if @payment_snapshots.present?
											.show-pulishers.search
												%h2{align: 'center'} Payment histories
												%br
												= form_for :search, url: admins_admin_path(@admin), method: 'get', html: {class: 'form-search', remote: true} do
													.input-group.full
														.col-md-3.no-padding
															= text_field_tag :key_payment_snapshots, params[:key_payment_snapshots], class: 'form-control pull-right radius-left', placeholder: 'Keywords'
														.col-md-2.no-padding
															= select_tag :category_payment_snapshots, options_for_select(PaymentSnapshot::CATEGORIES, params[:category_payment_snapshots]), prompt: 'Select Category', class: 'form-control'
														.col-md-3.no-padding
															= text_field_tag :start_at_payment_snapshots, nil, value: params[:start_at_payment_snapshots], class: 'form-control datepicker', placeholder: 'Start At'
														.col-md-3.no-padding
															= text_field_tag :end_at_payment_snapshots, nil, value: params[:end_at_payment_snapshots], class: 'form-control datepicker',  placeholder: 'End At'
														.col-md-1.no-padding
															= submit_tag :search, class: 'btn btn-info radius-right'
												#table-list-payment_snapshots
													= render 'admins/admins/list_payment_snapshots'
										- else
											= render "shared/empty_blank"
									#2.tab-pane
										- if @campaigns.present?
											.show-pulishers.search
												%h2{align: 'center'} Campaigns
												%br
												= form_for :search, url: admins_admin_path(@admin), method: 'get', html: {class: 'form-search', remote: true} do
													.input-group.full
														.col-md-3.no-padding
															= text_field_tag :key_campaigns, params[:key_campaigns], class: 'form-control pull-left radius-left', placeholder: 'Keywords'
														.col-md-2.no-padding
															= select_tag :status_campaign, options_for_select(Campaign::STATUSES, params[:status_campaign]), prompt: 'Select Status', class: 'form-control pull-left'
														.col-md-3.no-padding
															= text_field_tag :start_at_campaigns, nil, value: params[:start_at_campaigns], class: 'form-control datepicker pull-left', placeholder: 'Start At'
														.col-md-3.no-padding
															= text_field_tag :end_at_campaigns, nil, value: params[:end_at_campaigns], class: 'form-control datepicker pull-left',  placeholder: 'End At'
														.col-md-1.no-padding
															= submit_tag :Search, class: 'btn btn-info radius-right'
												#table-list-campaigns
													= render 'admins/admins/list_campaigns'
										- else
											= render "shared/empty_blank"
									#3.tab-pane
										- if @report_campaign_snapshots.present?
											.show-pulishers.search
												%h2{align: 'center'} Report campaign snapshots
												%br
												= form_for :search, url: admins_admin_path(@admin), method: 'get', html: {class: 'form-search', remote: true} do
													.input-group.full
														.col-md-5.no-padding
															= text_field_tag :key_report_campaign_snapshots, params[:key_report_campaign_snapshots], class: 'form-control pull-right radius-left', placeholder: 'Keywords'
														.col-md-3.no-padding
															= text_field_tag :start_at_report_campaign_snapshots, nil, value: params[:start_at_report_campaign_snapshots], class: 'form-control datepicker', placeholder: 'Start At'
														.col-md-3.no-padding
															= text_field_tag :end_at_report_campaign_snapshots, nil, value: params[:end_at_report_campaign_snapshots], class: 'form-control datepicker',  placeholder: 'End At'
														.col-md-1.no-padding
															= submit_tag :Search, class: 'btn btn-info radius-right'
												#table-list-report_campaign_snapshots
													= render 'admins/admins/list_report_campaign_snapshots'
										- else
											= render "shared/empty_blank"
									#4.tab-pane
										- if @verification_snapshots.present?
											.show-pulishers.search
												%h2{align: 'center'} Verification stories
												%br
												= form_for :search, url: admins_admin_path(@admin), method: 'get', html: {class: 'form-search', remote: true} do
													.input-group.full
														.col-md-3.no-padding
															= text_field_tag :key_verification_snapshots, params[:key_verification_snapshots], class: 'form-control pull-right radius-left', placeholder: 'Keywords'
														.col-md-2.no-padding
															= select_tag :status_verification_snapshots, options_for_select(VerificationSnapshot::STATUSES, params[:status_verification_snapshots]), prompt: 'Select Status', class: 'form-control pull-left'
														.col-md-3.no-padding
															= text_field_tag :start_at_verification_snapshots, nil, value: params[:start_at_verification_snapshots], class: 'form-control datepicker', placeholder: 'Start At'
														.col-md-3.no-padding
															= text_field_tag :end_at_verification_snapshots, nil, value: params[:end_at_verification_snapshots], class: 'form-control datepicker',  placeholder: 'End At'
														.col-md-1.no-padding
															= submit_tag :Search, class: 'btn btn-info radius-right'
												#table-list-verification_snapshots
													= render 'admins/admins/list_verification_snapshots'
										- else
											= render "shared/empty_blank"
									#5.tab-pane
										- if @activities.present?
											%h2{align: 'center'} Activities
											%br
											= form_for :search, url: admins_admin_path(@admin), method: 'get', html: {class: 'form-search', remote: true} do
												.input-group.full.search
													.col-md-5.no-padding
														= text_field_tag :key_activities, params[:key_activities], class: 'form-control pull-right radius-left', placeholder: 'Keywords'
													.col-md-3.no-padding
														= text_field_tag :start_at_activities, nil, value: params[:start_at_activities], class: 'form-control datepicker', placeholder: 'Start At'
													.col-md-3.no-padding
														= text_field_tag :end_at_activities, nil, value: params[:end_at_activities], class: 'form-control datepicker',  placeholder: 'End At'
													.col-md-1.no-padding
														= submit_tag :Search, class: 'btn btn-info radius-right'
											#table-list-activities
												= render 'admins/admins/list_activities'
										- else
											= render "shared/empty_blank"
							

app/views/admins/admins/show.js.erb
$('#table-list-payment_snapshots').html("<%= escape_javascript render partial: 'list_payment_snapshots', locals: {payment_snapshots: @payment_snapshots} %>");
$('#table-list-campaigns').html("<%= escape_javascript render partial: 'list_campaigns', locals: {campaigns: @campaigns} %>");
$('#table-list-report_campaign_snapshots').html("<%= escape_javascript render partial: 'list_report_campaign_snapshots', locals: {report_campaign_snapshots: @report_campaign_snapshots} %>");
$('#table-list-verification_snapshots').html("<%= escape_javascript render partial: 'list_verification_snapshots', locals: {verification_snapshots: @verification_snapshots} %>");
$('#table-list-activities').html("<%= escape_javascript render partial: 'list_activities', locals: {activities: @activities} %>");