config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: 'confirmations'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  mount Ckeditor::Engine => '/ckeditor'

  root "home#index"
  get 'contact', to: "home#index#contact"
  get 'health-check', to: 'home#health_check'
  get 'about-us', to: 'about_us#index'
  get 'faqs', to: 'faqs#index'
  get 'features', to: 'features#index'
  get 'how-it-works', to: 'how_it_works#index'
  get 'contact', to: 'contacts#index'
  get 'privacy-policy', to: 'privacy_policy#index'
  get 'gdpr-cpaground', to: 'gdpr#index'
  get 'thank_you/:id', to: 'home#thank_you', as: "thank_you"
  get 'waiting_verified/:id', to: 'home#waiting_verified', as: "waiting_verified"
  get 'under-maintenance', to: 'home#under_maintenance', as: 'under_maintenance'
  get '404-not-found', to: 'home#not_found_page', as: 'not_found_page'
  get 'lombok', to: 'home#lombok', as: 'lombok'
  resources :contacts
  resources :subscribers, only: [:create] do 
    collection do
      get :subscribe
      get :unsubscribe
    end
  end

  resources :xhrs do
    collection do
      get :cities
      get :get_box_report
      get :get_balances
      get :get_revenues
      get :get_commisions
      get :get_notifications
      get :get_campaign
      get :get_campaign_date_form
      get :get_offer_cr
      get :get_payment_owners
      get :get_convertion_report
      get :change_convertion_report
    end
  end

  namespace :admins do
    resources :dashboards
    resources :owners
    resources :invoice_owners do
      member do
        put :change_status
      end
    end
    resources :admins
    resources :account_managers do
      member do
        put :change_status
        get :detail_report
      end
      collection do
        get :multiple_action
      end
    end
    resources :publishers do
      member do
        put :change_status
        get :detail_report
      end
      collection do
        get :multiple_action
        get :list_email
      end
    end
    resources :campaigns do
      collection do
        get :multiple_action
        post :import
      end
      member do
        put :change_status
        get :click_notif
      end
    end
    resources :category_campaigns do
      collection do
        get :multiple_action
        get :multiple_action_targeting
        get :multiple_action_banner_image
        post :import
        post :import_per_offer
      end
      member do
        put :change_status
        delete :delete_targeting
        delete :delete_banner_image
      end
    end
    resources :report_campaign_snapshots do
      member do
        put :change_convertion_report
        delete :delete_convertion_report
      end
    end
    resources :contacts
    resources :web_settings
    resources :payment_snapshots do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :layout_themes do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :request_landing_pages do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
        get :click_notif
      end
    end
    resources :subscribers, only: [:index, :show, :destroy] do
      member do
        put :change_status
      end
    end
    resources :blogs do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :forums do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
        delete :delete_comment
      end
    end
    resources :feeds do
      collection do
        post :comment_create
      end
    end
    resources :invoices do
      member do
        put :change_status
      end
    end
    resources :groups do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :access_offers do
      collection do
        get :multiple_action
      end
    end
    resources :reports do
      collection do
        get :input
      end
      member do
        delete :delete_report_item
      end
      collection do
        get :multiple_action
      end
    end
    resources :informations do
      member do
        put :change_status
      end
      collection do
        get :multiple_action
      end
    end
    resources :permission_referral_publishers
    resources :commisions
    resources :payment_commisions do
      collection do
        get :multiple_action
      end
      member do
        put :change_status
      end
    end
    resources :messages
  end

  namespace :account_managers do
    resources :dashboards do
      collection do
        resources :rankings
      end
    end
    resources :campaigns do
      member do
        get :click_notif
        put :approvement
      end
    end
    resources :offers
    resources :profiles
    resources :activities
    resources :forums do
      member do
        delete :delete_comment
      end
    end
    resources :blogs do
      collection do
        post :comment_create
      end
    end
    resources :referrals
    resources :payments do
      member do
        get :click_notif
      end
    end
    resources :publishers do
      member do
        get :click_message
        get :detail_report
        put :change_status
        put :suspended
      end
    end
    resources :messages do
      collection do
        post :blast_message
      end
    end
    resources :feeds do
      collection do
        post :comment_create
        post :like_create
      end
    end
    resources :request_landing_pages do
      member do
        get :click_notif
      end
    end
    resources :notifications
    resources :groups do
      member do
        # put :change_status
        put :change_status_group_coverage
        get :click_notif
      end
    end
    resources :offers do
      member do
        get :click_notif
        put :checked
        put :change_status
      end
    end
    resources :reports
    resources :permission_referral_publishers
    resources :commisions
  end

  namespace :publishers do
    # get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :dashboards
    resources :campaigns do
      member do
        get :click_notif
      end
    end
    resources :offers do
      member do
        get :click_notif
        put :checked
        put :change_status
      end
    end
    resources :profiles
    resources :activities
    resources :forums
    resources :blogs do
      collection do
        post :comment_create
      end
    end
    resources :referrals
    resources :payments do
      member do
        get :click_notif
      end
    end
    resources :managers
    resources :messages
    resources :feeds do
      collection do
        post :comment_create
        post :like_create
      end
    end
    resources :request_landing_pages do
      member do
        get :click_notif
        put :change_status
      end
      collection do
        get :download_lp
      end
    end
    resources :notifications
    resources :groups do
      collection do
        post :join
      end
      member do
        get :click_notif
      end
    end
    resources :access_offers
    resources :reports
    resources :referral_publishers
    resources :commisions
    resources :payment_commisions do
      member do
        get :click_notif
      end
    end
    resources :offer_commisions
  end

  namespace :api do
    resources :lp do
      collection do
        get :track_visit
        get :postback
        get :get_campaigns
      end
    end
  end
  get 'postback', to: 'api/lp#postback', as: "postback"
end

app/models/access_offer.rb
class AccessOffer
  include Mongoid::Document
  field :publisher_id, type: Integer
  field :account_manager_id, type: Integer
  field :category_campaign_id, type: String
  field :status, type: String, default: 'approve'
  field :checked, type: Boolean, default: false
  field :message, type: String
  field :created_at, type: DateTime
  field :updated_at, type: DateTime

  index({ publisher_id: 1, account_manager_id: 1, category_campaign_id: 1, status: 1})

  before_create :before_create_service
  before_save :before_update_service

  scope :latest, ->{order(created_at: :desc)}
  scope :oldest, ->{order(created_at: :asc)}
  scope :approved, ->{where(status: "approve")}
  scope :banned, ->{where(status: "banned")}

  include TheAccessOffers::AccessOffersSearching

  # ------- STATUS --------
  APPROVE = 'approve'.freeze
  BANNED = 'banned'.freeze
  CHECKED = 'checked'.freeze

  STATUSES = [self::APPROVE, self::BANNED].freeze

  CHECKEDS = [["Yes", true], ["No", false]].freeze
  
  def status?
    if self.status == "approve"
      return "<label class='label label-success'>Approve</label>".html_safe
    else
      return "<label class='label label-danger'>Banned</label>".html_safe
    end
  end
  
  def label_checked?
    if self.checked == true
      return "<label class='label label-success'>Yes</label>".html_safe
    else
      return "<label class='label label-danger'>No</label>".html_safe
    end
  end

  def publisher
    publisher = Publisher.find_by(id: self.publisher_id)
  end

  def account_manager
    account_manager = AccountManager.find_by(id: self.account_manager_id)
  end

  def offer
    offer = CategoryCampaign.find_by(id: self.category_campaign_id)
  end

  private
    def before_create_service
      self.created_at = Time.zone.now
      self.updated_at = Time.zone.now
    end

    def before_update_service
      self.updated_at = Time.zone.now
    end
end

app/controllers/admins/access_offers_controller.rb
class Admins::AccessOffersController < Admins::ApplicationController
  before_action :check_profile
  before_action :class_name

  add_breadcrumb "dashboard", :admins_dashboards_path
  add_breadcrumb "access offers", :admins_access_offers_path

  def index
    @access_offers = collection.page(page).per(per_page)
    @collection_size = "(#{@access_offers.total_count})"
    
    respond_to do |format|
      format.html 
      format.xls
      format.js
    end
  end

  def multiple_action
    if params[:ids].present?
      collect = params[:ids]
      if params[:commit] == AccessOffer::APPROVE
        AccessOffer.where(:id.in => collect).each do |resource|
          unless resource.status == AccessOffer::APPROVE
            resource.status = AccessOffer::APPROVE
            resource.save
            @offer = resource.offer
            campaigns = Campaign.all_of({publisher_id: resource.publisher_id}, {category_campaign_id: resource.category_campaign_id})
            if campaigns.present?
              campaigns.each do |resource|
                resource.banned = false
                resource.save
              end
            end 
            create_activity(@offer, current_user.id, "Change status applied offer '#{@offer.name}' with code #{@offer.code}", "#{current_user.username} have successfully change status offer '#{@offer.name}' with code #{@offer.code} owned by #{resource.publisher.username} to #{resource.status}.")
            create_notification(@offer, resource.publisher_id, "Your applied offer '#{@offer.name}' with code #{@offer.code} has #{resource.status}", "Your applied offer '#{@offer.name}' with code #{@offer.code} has change status to #{resource.status}.")
            UserMailer.approve_access_offer(resource).deliver_now!
          end
        end
      elsif params[:commit] == AccessOffer::BANNED
        AccessOffer.where(:id.in => collect).each do |resource|
          unless resource.status == AccessOffer::BANNED
            resource.status = AccessOffer::BANNED
            resource.save
            @offer = resource.offer
            campaigns = Campaign.all_of({publisher_id: resource.publisher_id}, {category_campaign_id: resource.category_campaign_id})
            if campaigns.present?
              campaigns.each do |resource|
                resource.banned = true
                resource.save
              end
            end 
            create_activity(@offer, current_user.id, "Change status applied offer '#{@offer.name}' with code #{@offer.code}", "#{current_user.username} have successfully change status offer '#{@offer.name}' with code #{@offer.code} owned by #{resource.publisher.username} to #{resource.status}.")
            create_notification(@offer, resource.publisher_id, "Your applied offer '#{@offer.name}' with code #{@offer.code} has #{resource.status}", "Your applied offer '#{@offer.name}' with code #{@offer.code} has change status to #{resource.status}.")
            UserMailer.banned_access_offer(resource).deliver_now!
          end
        end
      elsif params[:commit] == "permission"
        AccessOffer.where(:id.in => collect).each do |resource|
          unless resource.checked == true
            resource.checked = true
            resource.save
            @offer = resource.offer
            create_activity(@offer, current_user.id, "Permission offer '#{@offer.name}' with code #{@offer.code}", "#{current_user.username} have successfully permission/approved offer '#{@offer.name}' with code #{@offer.code} owned by #{resource.publisher.username}.")
            create_notification(@offer, resource.publisher_id, "Your applied offer '#{@offer.name} with code #{@offer.code}' has #{resource.status}", "Now you can do get offer.")
            UserMailer.approve_access_offer(resource).deliver_now!
          end
        end
      end
      redirect_to admins_access_offers_path, notice: 'Status updated!'
    else
      redirect_to admins_access_offers_path, alert: 'Nothing checked!'
    end 
  end

  private
    def collection
      @access_offers = AccessOffer.latest.search_by(params)
    end

    def class_name
      @resource_name = 'Access Offer'
      @collection_name = 'Access Offers'
    end
end

app/controllers/publishers/access_offers_controller.rb
class Publishers::AccessOffersController < Publishers::ApplicationController
	before_action :check_profile
	before_action :class_name

	def create
		@access_offer = AccessOffer.new params_permit
		@access_offer.publisher_id = current_user.id
		@access_offer.account_manager_id = current_user.account_manager_id
		@access_offer.status = AccessOffer::APPROVE

		if @access_offer.save
      @offer = @access_offer.offer
			create_activity(@offer, current_user.id, "Applied offer '#{@offer.name}' with code #{@offer.code}", "#{@access_offer.publisher.username} have successfully submitted a request to create a campaign on offer '#{@offer.name}' with code #{@offer.code}.")
			create_notification(@offer, @access_offer.account_manager_id, "#{@access_offer.publisher.username} applied offer '#{@offer.name}' with code #{@offer.code}", "please verify your publisher data before approval offer.")
			UserMailer.apply_access_offer(@access_offer).deliver_now!
			redirect_to :back, notice: "You have successfully submitted a request to create a campaign on offer '#{@access_offer.offer.name}' with code #{@offer.code}, please wait, our team will verify your data first."
		else
			redirect_to :back, alert: "Unsuccessfully applied offer."
		end
	end

	private

		def params_permit
			params.require(:access_offer).permit(:publisher_id, :account_manager_id, :category_campaign_id, :status, :checked, :message)
		end

		def class_name
			@resource_name = 'Offer'
			@collection_name = 'Offers'
		end
end

app/views/admins/access_offers/_approve.html.haml
.access-offer
	- if @approve_offers.blank?
		.row
			.col-md-12
				= render "shared/empty_blank"
	- else
		- @approve_offers.each_with_index do |resource, index|
			.access-offer__info
				.row
					.col-md-1
						.avatar
							= image_tag resource.publisher.avatar.url(:thumb), class: "img-circle"
					.col-md-7
						.detail
							.user-entity
								= "<b>#{resource.publisher.username.titleize}</b>".html_safe
								%br
								%small
									= link_to resource.publisher.email, account_managers_publisher_path(resource.publisher)
								%br
								%small
									= resource.publisher.profile.city
					.col-md-2
						.checked-section
							- unless resource.checked?
								= form_for resource, url: '', method: 'put', html: { class: 'submit-checked-offer', data: {url: checked_account_managers_offer_path(resource.id)}} do |f|
									= button_tag "<i class='fa fa-check-circle-o'></i> APPROVE".html_safe, type: "sumbit", class: 'btn btn-sm btn-default', style: 'width:100%;'
					.col-md-2
						.status-section
							= form_for resource, url: '', method: 'put', html: { class: 'submit-status-offer', data: {url: change_status_account_managers_offer_path(resource.id)}} do |f|
								%span= f.hidden_field :status, value: "banned"
								= button_tag "<i class='fa fa-close'></i> BANNED".html_safe, type: "sumbit", class: 'btn btn-sm btn-danger', style: 'width:100%;'
				%hr

= paginate @approve_offers, remote: true, param_name: "page_approve"

app/views/admins/access_offers/_banned.html.haml
.access-offer
	- if @banned_offers.blank?
		.row
			.col-md-12
				= render "shared/empty_blank"
	- else
		- @banned_offers.each_with_index do |resource, index|
			.access-offer__info
				.row
					.col-md-1
						.avatar
							= image_tag resource.publisher.avatar.url(:thumb), class: "img-circle"
					.col-md-9
						.detail
							.user-entity
								= "<b>#{resource.publisher.username.titleize}</b>".html_safe
								%br
								%small
									= link_to resource.publisher.email, account_managers_publisher_path(resource.publisher)
								%br
								%small
									= resource.publisher.profile.city
					.col-md-2
						.status-section
							= form_for resource, url: '', method: 'put', html: { class: 'submit-status-offer', data: {url: change_status_account_managers_offer_path(resource.id)}} do |f|
								= f.hidden_field :status, value: "approve"
								= button_tag "<i class='fa fa-check-circle-o'></i> APPROVE".html_safe, type: "sumbit", class: 'btn btn-sm btn-default', style: 'width:100%;'
				%hr

= paginate @banned_offers, remote: true, param_name: "page_banned"

app/views/admins/access_offers/_detail.html.haml
.show-campaign
  .col-md-12.no-padding-m
    .row
      .col-md-12
        .row
          .col-md-3
            .form-group
              %b Category Name
          .col-md-9
            .form-group 
              = @offer.category_name
      .col-md-12
        .row
          .col-md-3
            .form-group
              %b Name
          .col-md-9
            .form-group 
              = @offer.name
      .col-md-12
        .row
          .col-md-3
            .form-group
              %b Link Offer
          .col-md-9
            .form-group 
              = @offer.link
      .col-md-12
        .row
          .col-md-3
            .form-group
              %b Action
          .col-md-9
            .form-group 
              = @offer.action
      .col-md-12
        .row
          .col-md-3
            .form-group
              %b Need Approval
          .col-md-9
            .form-group 
              = @offer.need_approval?
      .col-md-12
        .row
          .col-md-3
            .form-group
              %b Status
          .col-md-9
            .form-group 
              = @offer.status?
      .col-md-12
        .row
          .col-md-3
            .form-group
              %b Detail
          .col-md-9
            .form-group 
              = @offer.detail.present? ? @offer.detail.html_safe : "-"
      .col-md-12
        .row
          .col-md-3
            .form-group
              %b Created
          .col-md-9
            .form-group 
              = get_datetime(@offer.created_at)

app/views/admins/access_offers/_lists.html.haml
.responsive-tabel
  %table#example1.table.table-bordered.table-striped.tabel-width1
    %thead
      %tr
        %th
          = check_box_tag :check_all
        %th Publisher
        %th AM
        %th Permission
        %th Status
        %th{ width: "350px"} Offer
        %th{ width: "180px"} Created At
        %th{ width: "180px"} Updated At
    %tbody
      - if @access_offers.blank?
        %tr
          %td{ colspan: "8"} 
            = render "shared/empty_blank"
      - else
        - @access_offers.each_with_index do |resource, index|
          %tr
            %td
              = check_box_tag 'ids[]', resource.id
            %td
              = link_to resource.publisher.username, admins_publisher_path(resource.publisher)
            %td
              = link_to resource.account_manager.username, admins_account_manager_path(resource.account_manager)
            %td
              = resource.label_checked?
            %td
              = resource.status?
            %td
              = link_to resource.offer.name, admins_category_campaign_path(resource.offer)
            %td
              = get_datetime(resource.created_at)
            %td
              = get_datetime(resource.updated_at)

= paginate @access_offers, remote: true

:javascript
  $('.responsive-tabel').doubleScroll();

app/views/admins/access_offers/index.html.haml
#breadcrumbs
	= render "shared/admin/breadcrumbs"

%section.content.full-page
	.col-md-12
		.row.search
			.bg-white
				= form_for :search, url: admins_access_offers_path, method: 'get', html: {class: 'form-search', remote: true} do
					.input-group.full
						.col-md-3.no-padding
							= text_field_tag :key, params[:key], class: 'form-control pull-left', placeholder: 'Keywords'
						.col-md-2.no-padding
							= select_tag :checked, options_for_select(AccessOffer::CHECKEDS, params[:checked]), prompt: 'Select Permission', class: 'form-control no-border-radius'
						.col-md-2.no-padding
							= select_tag :status, options_for_select(AccessOffer::STATUSES, params[:status]), prompt: 'Select Status', class: 'form-control no-border-radius'
						.col-md-2.no-padding
							= text_field_tag :start_at, nil, value: params[:start_at], class: 'form-control datepicker', placeholder: 'Start At'
						.col-md-2.no-padding
							= text_field_tag :end_at, nil, value: params[:end_at], class: 'form-control datepicker',  placeholder: 'End At'
						.col-md-1.no-padding
							= submit_tag :search, class: 'btn btn-info radius-right'

	.row
		.col-xs-12.top-plus
			.box.box-m
				.box-body
					= form_for :multiple, url: multiple_action_admins_access_offers_path, method: 'get' do
						= submit_tag "permission", value: "permission", class: 'btn btn-sm btn-default no-radius no-border-right'
						= submit_tag AccessOffer::APPROVE, value: AccessOffer::APPROVE, class: 'btn btn-sm btn-default no-radius'
						= submit_tag AccessOffer::BANNED, value: AccessOffer::BANNED, class: 'btn btn-sm btn-default no-radius'
						#js-lists-access-offers
							= render 'admins/access_offers/lists'

app/views/admins/access_offers/index.js.erb
$('#breadcrumbs').html("<%= escape_javascript render partial: 'shared/admin/breadcrumbs' %>");
$('#js-lists-access-offers').html("<%= escape_javascript render partial: 'admins/access_offers/lists', locals: {access_offers: @access_offers} %>");

app/views/admins/access_offers/show.html.haml
#wrapper.content-detail-campaign-publisher
	.normalheader.small-header
		.hpanel
			.panel-body.responsive-title-page
				%a.small-header-action{:href => ""}
					.clip-header
						%i.fa.fa-arrow-up
				#hbreadcrumb.pull-right.m-t-lg.breadcrumb-capital.desktop
					%ol.breadcrumb.hbreadcrumb
						= render_breadcrumbs :tag => :li, :separator => ""
				%h2.font-light.m-b-xs
					%b (#{@offer.code}) #{@offer.name}
				%p Detail Offer

	.content.animate-panel.responsive-list-campaign
		.row
			.col-lg-12.m-t-md.content-campaign.responsive-panel-full

				.hpanel
					%ul.nav.nav-tabs
						%li.active
							%a{"aria-expanded" => "false", "data-toggle" => "tab", :href => "#tab-1"} 
								%i.fa.fa-file-text-o
								&nbsp; Detail
						%li
							%a{"aria-expanded" => "true", "data-toggle" => "tab", :href => "#tab-2"} 
								%i.fa.fa-check-square-o
								&nbsp; Approve
						%li
							%a{"aria-expanded" => "true", "data-toggle" => "tab", :href => "#tab-3"} 
								%i.fa.fa-close
								&nbsp; Banned
					.tab-content
						#tab-1.tab-pane.active
							.panel-body
								#js-detail-offer
									= render 'account_managers/offers/detail'

						#tab-2.tab-pane
							.panel-body
								.row
									.col-md-8.col-md-offset-2.no-padding-m
										= form_for :search, url: account_managers_offer_path(@offer), method: 'get', html: {class: 'form-search form-search-offers', remote: true} do
											.input-group.full
												.col-md-12.no-padding
													= text_field_tag :key, params[:key], class: 'form-control pull-left no-border-radius', placeholder: 'Keywords', autofocus: true
												.input-group-btn
													= submit_tag :Search, class: 'btn btn-primary no-border-radius'
										%br
										#js-approve-offer
											= render "account_managers/offers/approve"
						#tab-3.tab-pane
							.panel-body
								.row
									.col-md-8.col-md-offset-2.no-padding-m
										= form_for :search, url: account_managers_offer_path(@offer), method: 'get', html: {class: 'form-search form-search-offers', remote: true} do
											.input-group.full
												.col-md-12.no-padding
													= text_field_tag :key2, params[:key2], class: 'form-control pull-left no-border-radius', placeholder: 'Keywords', autofocus: true
												.input-group-btn
													= submit_tag :Search, class: 'btn btn-primary no-border-radius'
										%br
										#js-banned-offer
											= render 'account_managers/offers/banned'
						
	= render 'publishers/shared/footer'

app/views/admins/access_offers/show.js.erb
$('#js-approve-offer').html("<%= escape_javascript render partial: 'account_managers/offers/approve', locals: {approve_offers: @approve_offers} %>");
$('#js-banned-offer').html("<%= escape_javascript render partial: 'account_managers/offers/banned', locals: {banned_offers: @banned_offers} %>");